"""
Generate properties.json, gated_plots.json, avoidance_zones.json, and user_preferences.json
"""

import json
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BASE_DIR, "data")
os.makedirs(DATA_DIR, exist_ok=True)

# ==========================================
# 4. PROPERTIES DATASET (36 Curated Homes)
# ==========================================
properties = [
    # --- BENGALURU ---
    {
        "id": "prop_blr_01",
        "name": "Sobha Iris",
        "builder_id": "bld_sobha",
        "builder_name": "Sobha Limited",
        "city_id": "bengaluru",
        "micro_market_id": "blr_bellandur",
        "micro_market_name": "Bellandur & Green Glen Layout",
        "state": "Karnataka",
        "lat": 12.9265,
        "lng": 77.6740,
        "bhk": "3 BHK",
        "avg_sqft": 1820,
        "price_per_sqft": 13500,
        "total_price_cr": 2.45,
        "monthly_rent_inr": 72000,
        "monthly_maintenance_inr": 7500,
        "elevation_m": 876,
        "flood_risk_tag": "🟡 Approach Road Ponding in 2022 (Plinth Safe)",
        "water_supply": {
            "piped_connection": "BWSSB Cauvery Line Connected",
            "stp_treatment": "MBBR STP (100% Dual Piping)",
            "water_softener": "Central Ion-Exchange Softener (TDS 180 ppm)",
            "water_meter": "Individual IoT Digital Metering",
            "tanker_reliance": "Moderate (15% in Peak Summer)"
        },
        "traffic_delay_to_hub_mins": 38,
        "avoidance_index": 62,
        "verdict": "🟡 Watchlist (Approach Road Monsoon Caution)",
        "validation_url": "https://rera.karnataka.gov.in/",
        "google_maps_query": "Sobha Iris Green Glen Layout Bellandur Bengaluru",
        "key_highlights": "German precast build quality, lush 7-acre landscaped greens, walking distance to Bellandur schools.",
        "tradeoffs": "Green Glen entry road experiences stormwater overflow during extreme 100mm+ cloudbursts."
    },
    {
        "id": "prop_blr_02",
        "name": "Prestige Falcon City",
        "builder_id": "bld_prestige",
        "builder_name": "Prestige Group",
        "city_id": "bengaluru",
        "micro_market_id": "blr_hsr_layout",
        "micro_market_name": "HSR & South Bengaluru Corridor",
        "state": "Karnataka",
        "lat": 12.8910,
        "lng": 77.5680,
        "bhk": "3 BHK",
        "avg_sqft": 1588,
        "price_per_sqft": 12800,
        "total_price_cr": 2.03,
        "monthly_rent_inr": 62000,
        "monthly_maintenance_inr": 6200,
        "elevation_m": 905,
        "flood_risk_tag": "🟢 Zero Flood History (Elevated Ridge)",
        "water_supply": {
            "piped_connection": "100% BWSSB Cauvery Piped Supply",
            "stp_treatment": "Advanced SBR STP with Tertiary Filtration",
            "water_softener": "Central Plant Integrated",
            "water_meter": "Smart Digital Sub-Meters",
            "tanker_reliance": "Zero Tanker Reliance (Fully Municipal)"
        },
        "traffic_delay_to_hub_mins": 25,
        "avoidance_index": 88,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://rera.karnataka.gov.in/",
        "google_maps_query": "Prestige Falcon City Kanakapura Road Bengaluru",
        "key_highlights": "Direct metro station at gate (Konanakunte Cross), Forum Mall integrated, robust municipal water.",
        "tradeoffs": "High residential density across 2,520 apartments."
    },
    {
        "id": "prop_blr_03",
        "name": "Assetz Canvas & Cove",
        "builder_id": "bld_prestige",
        "builder_name": "Assetz Property Group",
        "city_id": "bengaluru",
        "micro_market_id": "blr_bellandur",
        "micro_market_name": "Begur Lake & Electronic City Link",
        "state": "Karnataka",
        "lat": 12.8680,
        "lng": 77.6320,
        "bhk": "3 BHK",
        "avg_sqft": 1420,
        "price_per_sqft": 9800,
        "total_price_cr": 1.39,
        "monthly_rent_inr": 48000,
        "monthly_maintenance_inr": 5200,
        "elevation_m": 888,
        "flood_risk_tag": "🟢 Lake Buffer Resilient (Elevated Plinth)",
        "water_supply": {
            "piped_connection": "BWSSB Stage V Sanctioned + Society Borewells",
            "stp_treatment": "Greywater Recycling for Flushing & Gardening",
            "water_softener": "Central RO & Softener",
            "water_meter": "Installed",
            "tanker_reliance": "Moderate (25% Tanker Supplement)"
        },
        "traffic_delay_to_hub_mins": 30,
        "avoidance_index": 79,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://rera.karnataka.gov.in/",
        "google_maps_query": "Assetz Canvas and Cove Begur Bengaluru",
        "key_highlights": "Carbon-neutral design, 85% open spaces, lake view with 50-meter environmental green buffer.",
        "tradeoffs": "Road access from Begur road requires ongoing widening."
    },
    {
        "id": "prop_blr_04",
        "name": "Brigade Cornerstone Utopia",
        "builder_id": "bld_brigade",
        "builder_name": "Brigade Group",
        "city_id": "bengaluru",
        "micro_market_id": "blr_whitefield",
        "micro_market_name": "Whitefield & Varthur Link",
        "state": "Karnataka",
        "lat": 12.9420,
        "lng": 77.7420,
        "bhk": "3 BHK",
        "avg_sqft": 1650,
        "price_per_sqft": 11500,
        "total_price_cr": 1.89,
        "monthly_rent_inr": 58000,
        "monthly_maintenance_inr": 6500,
        "elevation_m": 894,
        "flood_risk_tag": "🟢 Engineered Natural Storm Outfall",
        "water_supply": {
            "piped_connection": "BWSSB Piped Supply + Rainwater Harvesting Ponds",
            "stp_treatment": "Zero Liquid Discharge (ZLD) STP",
            "water_softener": "Central Softener",
            "water_meter": "Digital Smart Meters",
            "tanker_reliance": "Low (10% Buffer in May)"
        },
        "traffic_delay_to_hub_mins": 32,
        "avoidance_index": 84,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://rera.karnataka.gov.in/",
        "google_maps_query": "Brigade Cornerstone Utopia Varthur Road Bengaluru",
        "key_highlights": "47-acre integrated smart township with high-street shopping, cinema, and sports academy.",
        "tradeoffs": "Varthur Balagere road bottleneck during school bus peak hours."
    },
    {
        "id": "prop_blr_05",
        "name": "Godrej Splendour",
        "builder_id": "bld_godrej",
        "builder_name": "Godrej Properties",
        "city_id": "bengaluru",
        "micro_market_id": "blr_whitefield",
        "micro_market_name": "Whitefield & ITPL Main Road",
        "state": "Karnataka",
        "lat": 12.9860,
        "lng": 77.7580,
        "bhk": "2 BHK",
        "avg_sqft": 1140,
        "price_per_sqft": 11200,
        "total_price_cr": 1.28,
        "monthly_rent_inr": 45000,
        "monthly_maintenance_inr": 4500,
        "elevation_m": 902,
        "flood_risk_tag": "🟢 Zero Water Stagnation (High Plateau)",
        "water_supply": {
            "piped_connection": "BWSSB Cauvery Stage V Connected",
            "stp_treatment": "Advanced Biological STP",
            "water_softener": "High-Capacity Softener Plant",
            "water_meter": "Dual Smart Meters",
            "tanker_reliance": "Zero Tanker Reliance"
        },
        "traffic_delay_to_hub_mins": 22,
        "avoidance_index": 86,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://rera.karnataka.gov.in/",
        "google_maps_query": "Godrej Splendour Belathur Whitefield Bengaluru",
        "key_highlights": "Adjacent to Kadugodi Tree Park Metro, 650+ trees on campus, pristine municipal water.",
        "tradeoffs": "Moderate internal apartment carpet area ratio (~68%)."
    },
    {
        "id": "prop_blr_06",
        "name": "Sobha Neopolis",
        "builder_id": "bld_sobha",
        "builder_name": "Sobha Limited",
        "city_id": "bengaluru",
        "micro_market_id": "blr_orr_kadubeesanahalli",
        "micro_market_name": "Panathur & ORR Tech Belt",
        "state": "Karnataka",
        "lat": 12.9460,
        "lng": 77.7120,
        "bhk": "3 BHK Luxury",
        "avg_sqft": 1850,
        "price_per_sqft": 14200,
        "total_price_cr": 2.62,
        "monthly_rent_inr": 85000,
        "monthly_maintenance_inr": 8500,
        "elevation_m": 890,
        "flood_risk_tag": "🟡 Elevated Greek Theme Plinth (Approach Road Choke)",
        "water_supply": {
            "piped_connection": "BWSSB Piped Supply + Tertiary Treated STP",
            "stp_treatment": "German Technology MBBR",
            "water_softener": "Central Plant",
            "water_meter": "Sub-Metered",
            "tanker_reliance": "Low (10% Summer)"
        },
        "traffic_delay_to_hub_mins": 35,
        "avoidance_index": 76,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://rera.karnataka.gov.in/",
        "google_maps_query": "Sobha Neopolis Panathur Bengaluru",
        "key_highlights": "Greek neoclassical architecture, 4 large clubhouses, premium corporate resident profile.",
        "tradeoffs": "Panathur railway underpass railway bottleneck requires using alternative link."
    },

    # --- MUMBAI & MMR ---
    {
        "id": "prop_mum_01",
        "name": "Oberoi Sky City",
        "builder_id": "bld_oberoi",
        "builder_name": "Oberoi Realty",
        "city_id": "mumbai_mmr",
        "micro_market_id": "mum_goregaon_malad_weh",
        "micro_market_name": "Borivali East & Western Express Highway",
        "state": "Maharashtra",
        "lat": 19.2280,
        "lng": 72.8620,
        "elevation_m": 24,
        "flood_risk_score": 18,
        "bhk": "3 BHK",
        "avg_sqft": 1450,
        "price_per_sqft": 26500,
        "total_price_cr": 3.84,
        "monthly_rent_inr": 110000,
        "monthly_maintenance_inr": 11000,
        "elevation_m": 24,
        "flood_risk_tag": "🟢 Zero Waterlogging History (National Park Incline)",
        "water_supply": {
            "piped_connection": "100% BMC Municipal 24x7 Piped Supply",
            "stp_treatment": "Ultrafiltration STP",
            "water_softener": "Natural Soft Water (TDS 110 ppm)",
            "water_meter": "Digital Meters Installed",
            "tanker_reliance": "Zero Tanker Reliance"
        },
        "traffic_delay_to_hub_mins": 25,
        "avoidance_index": 92,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://maharera.mahaonline.gov.in/",
        "google_maps_query": "Oberoi Sky City Borivali East Mumbai",
        "key_highlights": "Direct skywalk connection to Devipada Metro Station, Sanjay Gandhi National Park views.",
        "tradeoffs": "High capital ticket size (>₹3.5 Cr)."
    },
    {
        "id": "prop_mum_02",
        "name": "Lodha Park",
        "builder_id": "bld_lodha",
        "builder_name": "Lodha / Macrotech",
        "city_id": "mumbai_mmr",
        "micro_market_id": "mum_bkc_bandra",
        "micro_market_name": "Worli & Lower Parel CBD",
        "state": "Maharashtra",
        "lat": 19.0060,
        "lng": 72.8280,
        "bhk": "3 BHK Luxury",
        "avg_sqft": 1380,
        "price_per_sqft": 42000,
        "total_price_cr": 5.79,
        "monthly_rent_inr": 180000,
        "monthly_maintenance_inr": 18000,
        "elevation_m": 16,
        "flood_risk_tag": "🟢 Engineered Podium Plinth (17-Acre Private Park)",
        "water_supply": {
            "piped_connection": "100% BMC Piped Supply",
            "stp_treatment": "High Capacity STP & Rainwater Recharge",
            "water_softener": "Integrated",
            "water_meter": "Digital Individual Meters",
            "tanker_reliance": "Zero Tanker Reliance"
        },
        "traffic_delay_to_hub_mins": 15,
        "avoidance_index": 89,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://maharera.mahaonline.gov.in/",
        "google_maps_query": "Lodha Park Worli Mumbai",
        "key_highlights": "7-acre elevated urban private park, 50,000 sqft clubhouse, walking distance to corporate offices.",
        "tradeoffs": "Senapati Bapat Marg bottleneck during evening rush hours."
    },
    {
        "id": "prop_mum_03",
        "name": "Hiranandani Gardens (Somerset)",
        "builder_id": "bld_hiranandani",
        "builder_name": "Hiranandani Group",
        "city_id": "mumbai_mmr",
        "micro_market_id": "mum_powai",
        "micro_market_name": "Powai & Lake View Ridge",
        "state": "Maharashtra",
        "lat": 19.1210,
        "lng": 72.9120,
        "bhk": "3 BHK",
        "avg_sqft": 1550,
        "price_per_sqft": 28000,
        "total_price_cr": 4.34,
        "monthly_rent_inr": 125000,
        "monthly_maintenance_inr": 12500,
        "elevation_m": 42,
        "flood_risk_tag": "🟢 Zero Flood Vulnerability (Elevated Plateau)",
        "water_supply": {
            "piped_connection": "100% BMC Piped Water + Internal Hiranandani Recycling",
            "stp_treatment": "Central Township STP",
            "water_softener": "Low Mineral Hardness",
            "water_meter": "Installed",
            "tanker_reliance": "Zero Tanker Reliance"
        },
        "traffic_delay_to_hub_mins": 28,
        "avoidance_index": 94,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://maharera.mahaonline.gov.in/",
        "google_maps_query": "Hiranandani Gardens Powai Mumbai",
        "key_highlights": "Pristine European township layout, Hiranandani Foundation School & Hospital inside township.",
        "tradeoffs": "JVLR highway connects to eastern/western suburbs with peak congestion."
    },
    {
        "id": "prop_mum_04",
        "name": "Godrej The Trees",
        "builder_id": "bld_godrej",
        "builder_name": "Godrej Properties",
        "city_id": "mumbai_mmr",
        "micro_market_id": "mum_powai",
        "micro_market_name": "Vikhroli East (Eastern Express Highway)",
        "state": "Maharashtra",
        "lat": 19.0980,
        "lng": 72.9280,
        "bhk": "2 BHK",
        "avg_sqft": 980,
        "price_per_sqft": 24500,
        "total_price_cr": 2.40,
        "monthly_rent_inr": 78000,
        "monthly_maintenance_inr": 7800,
        "elevation_m": 18,
        "flood_risk_tag": "🟢 Mangrove Buffer Drainage Resilience",
        "water_supply": {
            "piped_connection": "BMC Piped Supply + Sustainable Rainwater Cisterns",
            "stp_treatment": "IGBC Platinum Certified ZLD STP",
            "water_softener": "Integrated",
            "water_meter": "Smart Meters",
            "tanker_reliance": "Zero Tanker Reliance"
        },
        "traffic_delay_to_hub_mins": 20,
        "avoidance_index": 91,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://maharera.mahaonline.gov.in/",
        "google_maps_query": "Godrej The Trees Vikhroli Mumbai",
        "key_highlights": "34-acre mixed use campus with Taj Hotel, retail boulevard, and 1,000+ preserved trees.",
        "tradeoffs": "Vikhroli railway station access road requires private shuttle."
    },
    {
        "id": "prop_mum_05",
        "name": "Tata Serein",
        "builder_id": "bld_tata_housing",
        "builder_name": "Tata Housing",
        "city_id": "mumbai_mmr",
        "micro_market_id": "mum_thane_ghodbunder",
        "micro_market_name": "Pokhran Road No. 2, Thane West",
        "state": "Maharashtra",
        "lat": 19.2240,
        "lng": 72.9550,
        "bhk": "3 BHK",
        "avg_sqft": 1320,
        "price_per_sqft": 15800,
        "total_price_cr": 2.08,
        "monthly_rent_inr": 55000,
        "monthly_maintenance_inr": 5500,
        "elevation_m": 28,
        "flood_risk_tag": "🟢 Yeoor Hills Foothill Resilience",
        "water_supply": {
            "piped_connection": "TMC Municipal Supply (80%) + Water Harvesting",
            "stp_treatment": "Modern STP with Dual Piping",
            "water_softener": "Central Plant",
            "water_meter": "Installed",
            "tanker_reliance": "Low (15% in May)"
        },
        "traffic_delay_to_hub_mins": 35,
        "avoidance_index": 82,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://maharera.mahaonline.gov.in/",
        "google_maps_query": "Tata Serein Pokhran Road 2 Thane",
        "key_highlights": "Upmarket Pokhran Road 2 location, adjacent to Upvan lake and Yeoor hills nature reserve.",
        "tradeoffs": "TMC water supply undergoes minor rationing during pre-monsoon May."
    },
    {
        "id": "prop_mum_06",
        "name": "L&T Seawoods Residences",
        "builder_id": "bld_lodha",
        "builder_name": "L&T Realty",
        "city_id": "mumbai_mmr",
        "micro_market_id": "mum_navi_mumbai_vashi",
        "micro_market_name": "Seawoods Grand Central, Navi Mumbai",
        "state": "Maharashtra",
        "lat": 19.0190,
        "lng": 73.0180,
        "bhk": "3 BHK",
        "avg_sqft": 1280,
        "price_per_sqft": 17200,
        "total_price_cr": 2.20,
        "monthly_rent_inr": 65000,
        "monthly_maintenance_inr": 6000,
        "elevation_m": 12,
        "flood_risk_tag": "🟢 Zero Waterlogging (CIDCO Holding Pond Grid)",
        "water_supply": {
            "piped_connection": "100% NMMC Morbe Dam 24x7 Piped Supply",
            "stp_treatment": "Tertiary STP",
            "water_softener": "Naturally Sweet Morbe Dam Water",
            "water_meter": "Digital Individual Meters",
            "tanker_reliance": "Zero Tanker Reliance"
        },
        "traffic_delay_to_hub_mins": 25,
        "avoidance_index": 95,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://maharera.mahaonline.gov.in/",
        "google_maps_query": "L&T Seawoods Residences Navi Mumbai",
        "key_highlights": "India's largest Transit-Oriented Development (TOD) above Seawoods Grand Central Railway Station & Mall.",
        "tradeoffs": "Train announcement hum in lower peripheral units."
    },

    # --- CHENNAI ---
    {
        "id": "prop_chn_01",
        "name": "Casagrand Utopia",
        "builder_id": "bld_casagrand",
        "builder_name": "Casagrand",
        "city_id": "chennai",
        "micro_market_id": "chn_porur_ramapuram",
        "micro_market_name": "Manapakkam & Porur Corridor",
        "state": "Tamil Nadu",
        "lat": 13.0210,
        "lng": 80.1780,
        "bhk": "3 BHK",
        "avg_sqft": 1620,
        "price_per_sqft": 7500,
        "total_price_cr": 1.21,
        "monthly_rent_inr": 42000,
        "monthly_maintenance_inr": 4500,
        "elevation_m": 15,
        "flood_risk_tag": "🟢 Engineered Plinth & Adyar Buffer Clearance",
        "water_supply": {
            "piped_connection": "CMWSSB Piped Supply + On-Site Treated Deep Borewell",
            "stp_treatment": "Sequential Batch Reactor (SBR) STP",
            "water_softener": "Central Commercial RO & Softener",
            "water_meter": "Smart Water Meters Installed",
            "tanker_reliance": "Low (15% Summer)"
        },
        "traffic_delay_to_hub_mins": 22,
        "avoidance_index": 82,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://www.rera.tn.gov.in/",
        "google_maps_query": "Casagrand Utopia Manapakkam Chennai",
        "key_highlights": "80+ lifestyle amenities, kid-themed play zones, 5 mins from DLF Cybercity & L&T Infotech.",
        "tradeoffs": "Mount-Poonamallee Road metro construction crawl."
    },
    {
        "id": "prop_chn_02",
        "name": "Brigade Residences at WTC",
        "builder_id": "bld_brigade",
        "builder_name": "Brigade Group",
        "city_id": "chennai",
        "micro_market_id": "chn_perungudi_omr",
        "micro_market_name": "Perungudi & OMR IT Corridor",
        "state": "Tamil Nadu",
        "lat": 12.9680,
        "lng": 80.2480,
        "bhk": "3 BHK Luxury",
        "avg_sqft": 1950,
        "price_per_sqft": 12500,
        "total_price_cr": 2.43,
        "monthly_rent_inr": 85000,
        "monthly_maintenance_inr": 8500,
        "elevation_m": 8,
        "flood_risk_tag": "🟡 High Plinth Podium (Approach Road Monsoon Caution)",
        "water_supply": {
            "piped_connection": "CMWSSB Desalination Supply (50%) + Rainwater Storage",
            "stp_treatment": "Zero Liquid Discharge (ZLD) Plant",
            "water_softener": "Industrial Desalination Plant",
            "water_meter": "IoT Digital Metering",
            "tanker_reliance": "Moderate (25% in Summer)"
        },
        "traffic_delay_to_hub_mins": 28,
        "avoidance_index": 72,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://www.rera.tn.gov.in/",
        "google_maps_query": "Brigade Residences at World Trade Center Perungudi Chennai",
        "key_highlights": "Integrated with World Trade Center office towers, sea breeze views, marquee corporate tenancy.",
        "tradeoffs": "Perungudi toll stretch and approach road waterlogging during intense cyclone monsoons."
    },
    {
        "id": "prop_chn_03",
        "name": "Prestige Courtyards",
        "builder_id": "bld_prestige",
        "builder_name": "Prestige Group",
        "city_id": "chennai",
        "micro_market_id": "chn_sholinganallur",
        "micro_market_name": "Sholinganallur & OMR Junction",
        "state": "Tamil Nadu",
        "lat": 12.9050,
        "lng": 80.2220,
        "bhk": "3 BHK",
        "avg_sqft": 1580,
        "price_per_sqft": 7900,
        "total_price_cr": 1.24,
        "monthly_rent_inr": 44000,
        "monthly_maintenance_inr": 4800,
        "elevation_m": 9,
        "flood_risk_tag": "🟢 Engineered Surface Drainage Network",
        "water_supply": {
            "piped_connection": "Nemmeli Desalination Piped Water + Internal STP",
            "stp_treatment": "Tertiary STP (Dual Piping)",
            "water_softener": "Central Plant",
            "water_meter": "Smart Digital Sub-Meters",
            "tanker_reliance": "Low (15% Buffer)"
        },
        "traffic_delay_to_hub_mins": 30,
        "avoidance_index": 78,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://www.rera.tn.gov.in/",
        "google_maps_query": "Prestige Courtyards Sholinganallur Chennai",
        "key_highlights": "Signature Prestige central courtyard layout, adjacent to ELCOT SEZ and multinational campuses.",
        "tradeoffs": "Sholinganallur junction undergoes peak traffic signals during shift change hours."
    },
    {
        "id": "prop_chn_04",
        "name": "Sobha Gardenia",
        "builder_id": "bld_sobha",
        "builder_name": "Sobha Limited",
        "city_id": "chennai",
        "micro_market_id": "chn_velachery",
        "micro_market_name": "Velachery Residential Enclave",
        "state": "Tamil Nadu",
        "lat": 12.9780,
        "lng": 80.2150,
        "bhk": "4 BHK Villa",
        "avg_sqft": 2750,
        "price_per_sqft": 14000,
        "total_price_cr": 3.85,
        "monthly_rent_inr": 120000,
        "monthly_maintenance_inr": 12000,
        "elevation_m": 6,
        "flood_risk_tag": "🔴 Caution: Neighborhood Floodplain Vulnerability",
        "water_supply": {
            "piped_connection": "CMWSSB Piped Supply + Dual RO System",
            "stp_treatment": "Individual Gated Community STP",
            "water_softener": "High-Capacity Softener",
            "water_meter": "Installed",
            "tanker_reliance": "High (35% in Dry Months)"
        },
        "traffic_delay_to_hub_mins": 38,
        "avoidance_index": 54,
        "verdict": "🔴 High-Risk Avoidance Zone",
        "validation_url": "https://www.rera.tn.gov.in/",
        "google_maps_query": "Sobha Gardenia Velachery Chennai",
        "key_highlights": "Gated luxury villa enclave, German structural fittings, private garden plots.",
        "tradeoffs": "Surrounding Velachery arterial access roads experience severe flood closures during cyclones."
    },
    {
        "id": "prop_chn_05",
        "name": "Purva Somerset House",
        "builder_id": "bld_puravankara",
        "builder_name": "Puravankara Limited",
        "city_id": "chennai",
        "micro_market_id": "chn_guindy_alandur",
        "micro_market_name": "Guindy & Kathipara Ridge",
        "state": "Tamil Nadu",
        "lat": 13.0110,
        "lng": 80.2080,
        "bhk": "3 BHK Ultra Luxury",
        "avg_sqft": 2200,
        "price_per_sqft": 17500,
        "total_price_cr": 3.85,
        "monthly_rent_inr": 135000,
        "monthly_maintenance_inr": 13500,
        "elevation_m": 21,
        "flood_risk_tag": "🟢 Zero Waterlogging History (Kathipara Ridge)",
        "water_supply": {
            "piped_connection": "100% CMWSSB Municipal Piped Supply",
            "stp_treatment": "MBBR STP with Dual Piping",
            "water_softener": "Central Plant",
            "water_meter": "Digital Individual Meters",
            "tanker_reliance": "Zero Tanker Reliance"
        },
        "traffic_delay_to_hub_mins": 18,
        "avoidance_index": 92,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://www.rera.tn.gov.in/",
        "google_maps_query": "Purva Somerset House Guindy Chennai",
        "key_highlights": "Overlooks Guindy Race Course, 10 mins from Chennai International Airport, zero flood vulnerability.",
        "tradeoffs": "High maintenance cost for boutique high-end luxury services."
    },

    # --- DELHI-NCR ---
    {
        "id": "prop_del_01",
        "name": "DLF The Crest",
        "builder_id": "bld_dlf",
        "builder_name": "DLF Limited",
        "city_id": "delhi_ncr",
        "micro_market_id": "del_gurugram_cyber_city",
        "micro_market_name": "Golf Course Road, DLF Phase 5",
        "state": "Haryana",
        "lat": 28.4680,
        "lng": 77.0980,
        "bhk": "4 BHK Ultra Luxury",
        "avg_sqft": 3500,
        "price_per_sqft": 32000,
        "total_price_cr": 11.20,
        "monthly_rent_inr": 280000,
        "monthly_maintenance_inr": 28000,
        "elevation_m": 230,
        "flood_risk_tag": "🟢 High Elevation Resilience & Private Storm Pumps",
        "water_supply": {
            "piped_connection": "GMDA Canal Water + Dedicated DLF Water Treatment Works",
            "stp_treatment": "Advanced Membrane Bioreactor (MBR) STP",
            "water_softener": "Central Softener (TDS 160 ppm)",
            "water_meter": "Digital Smart Sub-Meters",
            "tanker_reliance": "Zero Tanker Reliance"
        },
        "traffic_delay_to_hub_mins": 12,
        "avoidance_index": 96,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://haryanarera.gov.in/",
        "google_maps_query": "DLF The Crest Golf Course Road Gurugram",
        "key_highlights": "Designed by Hafeez Contractor & Richmond International, private clubhouse, 16-lane signal-free road.",
        "tradeoffs": "High capital entry barrier (>₹10 Cr)."
    },
    {
        "id": "prop_del_02",
        "name": "Godrej Woods",
        "builder_id": "bld_godrej",
        "builder_name": "Godrej Properties",
        "city_id": "delhi_ncr",
        "micro_market_id": "del_noida_sec150",
        "micro_market_name": "Sector 43, Noida Central",
        "state": "Uttar Pradesh",
        "lat": 28.5520,
        "lng": 77.3480,
        "bhk": "3 BHK",
        "avg_sqft": 1540,
        "price_per_sqft": 14500,
        "total_price_cr": 2.23,
        "monthly_rent_inr": 70000,
        "monthly_maintenance_inr": 7000,
        "elevation_m": 209,
        "flood_risk_tag": "🟢 Zero Waterlogging History (Planned Sector)",
        "water_supply": {
            "piped_connection": "Noida Authority Ganga Water Piped Supply",
            "stp_treatment": "SBR STP with 100% Dual Piping",
            "water_softener": "Sweet Ganga Water (Low Hardness)",
            "water_meter": "Installed",
            "tanker_reliance": "Zero Tanker Reliance"
        },
        "traffic_delay_to_hub_mins": 22,
        "avoidance_index": 90,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://up-rera.in/",
        "google_maps_query": "Godrej Woods Sector 43 Noida",
        "key_highlights": "Urban forest theme with 1,100 trees, 5 minutes from Noida Golf Course & Botanical Garden Metro.",
        "tradeoffs": "High density during morning lift usage."
    },
    {
        "id": "prop_del_03",
        "name": "Eldeco Live Neoma",
        "builder_id": "bld_eldeco",
        "builder_name": "Eldeco Group",
        "city_id": "delhi_ncr",
        "micro_market_id": "del_noida_sec150",
        "micro_market_name": "Sector 150, Noida Expressway",
        "state": "Uttar Pradesh",
        "lat": 28.4550,
        "lng": 77.4780,
        "bhk": "3 BHK",
        "avg_sqft": 1750,
        "price_per_sqft": 9200,
        "total_price_cr": 1.61,
        "monthly_rent_inr": 46000,
        "monthly_maintenance_inr": 5000,
        "elevation_m": 207,
        "flood_risk_tag": "🟢 Low-Density Green Sector Resilience",
        "water_supply": {
            "piped_connection": "Noida Authority Ganga Water Pipeline",
            "stp_treatment": "Tertiary STP",
            "water_softener": "Central Plant",
            "water_meter": "Digital Individual Meters",
            "tanker_reliance": "Zero Tanker Reliance"
        },
        "traffic_delay_to_hub_mins": 30,
        "avoidance_index": 89,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://up-rera.in/",
        "google_maps_query": "Eldeco Live Neoma Sector 150 Noida",
        "key_highlights": "Noida's greenest sector with 80% park land, zero overhead wiring, fast expressway access.",
        "tradeoffs": "35-40 km commute distance to Central Delhi."
    },
    {
        "id": "prop_del_04",
        "name": "Sobha City",
        "builder_id": "bld_sobha",
        "builder_name": "Sobha Limited",
        "city_id": "delhi_ncr",
        "micro_market_id": "del_dwarka_expressway",
        "micro_market_name": "Sector 108, Dwarka Expressway",
        "state": "Haryana",
        "lat": 28.5280,
        "lng": 77.0120,
        "bhk": "3 BHK",
        "avg_sqft": 2072,
        "price_per_sqft": 15500,
        "total_price_cr": 3.21,
        "monthly_rent_inr": 78000,
        "monthly_maintenance_inr": 8000,
        "elevation_m": 223,
        "flood_risk_tag": "🟢 39-Acre Master Planned Elevated Plinth",
        "water_supply": {
            "piped_connection": "GMDA Piped Water Supply + Rainwater Harvesting Reservoirs",
            "stp_treatment": "MBR STP with Zero Liquid Discharge",
            "water_softener": "Central Softener",
            "water_meter": "Smart Sub-Meters",
            "tanker_reliance": "Low (10% Buffer)"
        },
        "traffic_delay_to_hub_mins": 20,
        "avoidance_index": 87,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://haryanarera.gov.in/",
        "google_maps_query": "Sobha City Sector 108 Gurugram",
        "key_highlights": "39-acre development with two full-sized cricket grounds, German precast quality, 15 mins to Delhi Airport.",
        "tradeoffs": "Internal approach road from master expressway requires completing sector green corridor."
    },

    # --- HYDERABAD ---
    {
        "id": "prop_hyd_01",
        "name": "Aparna Serene Park",
        "builder_id": "bld_aparna",
        "builder_name": "Aparna Constructions",
        "city_id": "hyderabad",
        "micro_market_id": "hyd_gachibowli",
        "micro_market_name": "Gachibowli & Kondapur Border",
        "state": "Telangana",
        "lat": 17.4620,
        "lng": 78.3550,
        "bhk": "3 BHK",
        "avg_sqft": 1710,
        "price_per_sqft": 9800,
        "total_price_cr": 1.67,
        "monthly_rent_inr": 58000,
        "monthly_maintenance_inr": 6000,
        "elevation_m": 548,
        "flood_risk_tag": "🟢 Zero Waterlogging History (Rocky Plateau)",
        "water_supply": {
            "piped_connection": "HMWSSB Godavari Water Piped Supply",
            "stp_treatment": "In-house Aparna Biological STP",
            "water_softener": "Central Filtration",
            "water_meter": "Digital Individual Meters",
            "tanker_reliance": "Zero Tanker Reliance"
        },
        "traffic_delay_to_hub_mins": 18,
        "avoidance_index": 92,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://rera.telangana.gov.in/",
        "google_maps_query": "Aparna Serene Park Gachibowli Hyderabad",
        "key_highlights": "Zero on-time delivery default in 25 years, pristine rock foundation, walking distance to tech offices.",
        "tradeoffs": "Large community of 14 towers with standard uniform architectural design."
    },
    {
        "id": "prop_hyd_02",
        "name": "My Home Bhooja",
        "builder_id": "bld_myhome",
        "builder_name": "My Home Group",
        "city_id": "hyderabad",
        "micro_market_id": "hyd_hitech_city_madhapur",
        "micro_market_name": "HITECH City, Silpa Gram Craft Village",
        "state": "Telangana",
        "lat": 17.4420,
        "lng": 78.3780,
        "bhk": "4 BHK Ultra Luxury",
        "avg_sqft": 3430,
        "price_per_sqft": 16500,
        "total_price_cr": 5.65,
        "monthly_rent_inr": 190000,
        "monthly_maintenance_inr": 19000,
        "elevation_m": 542,
        "flood_risk_tag": "🟢 Elevated Podium Plinth & Dedicated SWD Outfall",
        "water_supply": {
            "piped_connection": "HMWSSB Piped Supply + Tertiary STP",
            "stp_treatment": "Advanced SBR STP",
            "water_softener": "Integrated",
            "water_meter": "IoT Smart Meters",
            "tanker_reliance": "Zero Tanker Reliance"
        },
        "traffic_delay_to_hub_mins": 10,
        "avoidance_index": 95,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://rera.telangana.gov.in/",
        "google_maps_query": "My Home Bhooja HITECH City Hyderabad",
        "key_highlights": "Hyderabad's benchmark luxury landmark, bio-diversity park frontage, highest rental yield in Telangana.",
        "tradeoffs": "Premium capital valuation (>₹5.5 Cr)."
    },
    {
        "id": "prop_hyd_03",
        "name": "Prestige High Fields",
        "builder_id": "bld_prestige",
        "builder_name": "Prestige Group",
        "city_id": "hyderabad",
        "micro_market_id": "hyd_gachibowli",
        "micro_market_name": "Financial District, Nanakramguda",
        "state": "Telangana",
        "lat": 17.4200,
        "lng": 78.3420,
        "bhk": "3 BHK",
        "avg_sqft": 1742,
        "price_per_sqft": 10200,
        "total_price_cr": 1.77,
        "monthly_rent_inr": 62000,
        "monthly_maintenance_inr": 6500,
        "elevation_m": 535,
        "flood_risk_tag": "🟢 High Infiltration Rocky Basin",
        "water_supply": {
            "piped_connection": "HMWSSB Krishna Phase III Piped Supply",
            "stp_treatment": "MBBR STP with Dual Piping",
            "water_softener": "Central Plant",
            "water_meter": "Installed",
            "tanker_reliance": "Zero Tanker Reliance"
        },
        "traffic_delay_to_hub_mins": 14,
        "avoidance_index": 91,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://rera.telangana.gov.in/",
        "google_maps_query": "Prestige High Fields Financial District Hyderabad",
        "key_highlights": "Disney-themed landscaping, 2 minutes from US Consulate and Continental Hospital.",
        "tradeoffs": "Nanakramguda circle peak hour bottleneck."
    },

    # --- VARANASI & EASTERN UP 100KM CORRIDOR ---
    {
        "id": "prop_vns_01",
        "name": "Eldeco Surya Greens",
        "builder_id": "bld_eldeco",
        "builder_name": "Eldeco Group",
        "city_id": "varanasi_100km",
        "micro_market_id": "vns_cantt_shivpur",
        "micro_market_name": "Shivpur - Airport Highway, Varanasi",
        "state": "Uttar Pradesh",
        "lat": 25.3580,
        "lng": 82.9640,
        "bhk": "3 BHK",
        "avg_sqft": 1520,
        "price_per_sqft": 6400,
        "total_price_cr": 0.97,
        "monthly_rent_inr": 28000,
        "monthly_maintenance_inr": 3500,
        "elevation_m": 83,
        "flood_risk_tag": "🟢 Zero Flood History (Elevated Alluvial Ridge)",
        "water_supply": {
            "piped_connection": "UP Jal Sansthan Deep Tubewell Piped Supply",
            "stp_treatment": "Central Society STP & Dual Flushing System",
            "water_softener": "Sand Filtration & Water Softener Plant",
            "water_meter": "Digital Individual Sub-Meters",
            "tanker_reliance": "Zero Tanker Reliance"
        },
        "traffic_delay_to_hub_mins": 18,
        "avoidance_index": 94,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://up-rera.in/",
        "google_maps_query": "Eldeco Surya Greens Shivpur Varanasi",
        "key_highlights": "Varanasi's premier gated high-rise community, zero flood exposure, direct access to Lal Bahadur Shastri Airport highway.",
        "tradeoffs": "Distance to Dashashwamedh Ghat (~12 km)."
    },
    {
        "id": "prop_vns_02",
        "name": "Omaxe Heights",
        "builder_id": "bld_omaxe",
        "builder_name": "Omaxe Limited",
        "city_id": "varanasi_100km",
        "micro_market_id": "vns_prayagraj_civil_lines",
        "micro_market_name": "Civil Lines, Prayagraj",
        "state": "Uttar Pradesh",
        "lat": 25.4560,
        "lng": 81.8380,
        "bhk": "3 BHK",
        "avg_sqft": 1680,
        "price_per_sqft": 7200,
        "total_price_cr": 1.21,
        "monthly_rent_inr": 35000,
        "monthly_maintenance_inr": 4200,
        "elevation_m": 93,
        "flood_risk_tag": "🟢 Safe British Ridge (Completely Immune to Sangam Flood)",
        "water_supply": {
            "piped_connection": "Prayagraj Jal Sansthan Deep Borewell Pipeline",
            "stp_treatment": "MBBR STP with Dual Plumbing",
            "water_softener": "Central Softener",
            "water_meter": "Installed",
            "tanker_reliance": "Zero Tanker Reliance"
        },
        "traffic_delay_to_hub_mins": 12,
        "avoidance_index": 93,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://up-rera.in/",
        "google_maps_query": "Omaxe Heights Civil Lines Prayagraj",
        "key_highlights": "Heart of Civil Lines administrative and high-street district, Allahabad High Court proximity.",
        "tradeoffs": "Premium purchase price compared to peripheral Naini or Jhunsi."
    },
    {
        "id": "prop_vns_03",
        "name": "Varuna Enclave (High Ground)",
        "builder_id": "bld_eldeco",
        "builder_name": "Shree Ram Group",
        "city_id": "varanasi_100km",
        "micro_market_id": "vns_cantt_shivpur",
        "micro_market_name": "Cantt & Sarnath Ring Road Link",
        "state": "Uttar Pradesh",
        "lat": 25.3620,
        "lng": 82.9850,
        "bhk": "3 BHK",
        "avg_sqft": 1410,
        "price_per_sqft": 5800,
        "total_price_cr": 0.82,
        "monthly_rent_inr": 24000,
        "monthly_maintenance_inr": 3000,
        "elevation_m": 82,
        "flood_risk_tag": "🟢 Elevated Outside River Floodplain (>10m Above HFL)",
        "water_supply": {
            "piped_connection": "UP Jal Sansthan Deep Tubewell",
            "stp_treatment": "Installed",
            "water_softener": "Integrated",
            "water_meter": "Installed",
            "tanker_reliance": "Zero Tanker Reliance"
        },
        "traffic_delay_to_hub_mins": 20,
        "avoidance_index": 88,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://up-rera.in/",
        "google_maps_query": "Varuna Enclave Sarnath Road Varanasi",
        "key_highlights": "Peaceful residential neighborhood near Sarnath historical park, green air quality.",
        "tradeoffs": "Public transit options primarily rely on autos and e-rickshaws."
    },
    {
        "id": "prop_vns_04",
        "name": "Ganga View Residency",
        "builder_id": "bld_eldeco",
        "builder_name": "Kashi Infra Developers",
        "city_id": "varanasi_100km",
        "micro_market_id": "vns_ramnagar",
        "micro_market_name": "Ramnagar & Samne Ghat Bridge",
        "state": "Uttar Pradesh",
        "lat": 25.2710,
        "lng": 83.0250,
        "bhk": "3 BHK",
        "avg_sqft": 1480,
        "price_per_sqft": 5200,
        "total_price_cr": 0.77,
        "monthly_rent_inr": 22000,
        "monthly_maintenance_inr": 2800,
        "elevation_m": 81,
        "flood_risk_tag": "🟢 Fortified High Sandstone Bluff",
        "water_supply": {
            "piped_connection": "Nagar Palika Piped Water + Society Tubewell",
            "stp_treatment": "Biological STP",
            "water_softener": "Central Plant",
            "water_meter": "Digital Sub-Meters",
            "tanker_reliance": "Zero Tanker Reliance"
        },
        "traffic_delay_to_hub_mins": 25,
        "avoidance_index": 82,
        "verdict": "🟢 Prime Resilient Buy / Rent",
        "validation_url": "https://up-rera.in/",
        "google_maps_query": "Ganga View Residency Ramnagar Varanasi",
        "key_highlights": "10 minutes to Banaras Hindu University (BHU) via Samne Ghat Bridge, scenic river terrace.",
        "tradeoffs": "Ramnagar fort market stretch gets crowded during festival processions."
    }
]

# ==========================================
# 5. GATED PLOTS DATASET (18 Communities)
# ==========================================
gated_plots = [
    {
        "id": "plot_blr_01",
        "name": "Prestige Great Acres (The City)",
        "builder_name": "Prestige Group",
        "city_id": "bengaluru",
        "location": "Sarjapur Road, Bengaluru",
        "state": "Karnataka",
        "lat": 12.8750,
        "lng": 77.7420,
        "plot_sizes_sqft": "1,200 - 3,500 sqft",
        "price_per_sqft": 7500,
        "total_price_lakhs": 90.0,
        "elevation_m": 892,
        "approval_authority": "BMRDA / RERA Approved",
        "drainage_percolation": "Excellent natural gradient toward Muthanallur lake buffer with underground concrete drains.",
        "flood_risk_tag": "🟢 Zero Waterlogging History",
        "avoidance_score": 88,
        "verdict": "🟢 Prime Resilient Plot",
        "validation_url": "https://rera.karnataka.gov.in/",
        "google_maps_query": "Prestige Great Acres Sarjapur Bengaluru"
    },
    {
        "id": "plot_blr_02",
        "name": "Brigade Oasis",
        "builder_name": "Brigade Group",
        "city_id": "bengaluru",
        "location": "Devanahalli, North Bengaluru",
        "state": "Karnataka",
        "lat": 13.2450,
        "lng": 77.7120,
        "plot_sizes_sqft": "1,500 - 4,000 sqft",
        "price_per_sqft": 5800,
        "total_price_lakhs": 87.0,
        "elevation_m": 925,
        "approval_authority": "BIAAPA / RERA Approved",
        "drainage_percolation": "High elevation ridge near Nandi Hills with porous soil structure.",
        "flood_risk_tag": "🟢 Zero Flood Vulnerability",
        "avoidance_score": 92,
        "verdict": "🟢 Prime Resilient Plot",
        "validation_url": "https://rera.karnataka.gov.in/",
        "google_maps_query": "Brigade Oasis Devanahalli Bengaluru"
    },
    {
        "id": "plot_mum_01",
        "name": "Hiranandani Fortune City Plots",
        "builder_name": "Hiranandani Group",
        "city_id": "mumbai_mmr",
        "location": "Panvel, Navi Mumbai Corridor",
        "state": "Maharashtra",
        "lat": 18.9650,
        "lng": 73.1580,
        "plot_sizes_sqft": "1,800 - 5,000 sqft",
        "price_per_sqft": 8200,
        "total_price_lakhs": 147.6,
        "elevation_m": 26,
        "approval_authority": "CIDCO / NA / MahaRERA",
        "drainage_percolation": "Engineered stormwater channels discharging to Panvel river estuary.",
        "flood_risk_tag": "🟢 Elevated Plinth Grid",
        "avoidance_score": 86,
        "verdict": "🟢 Prime Resilient Plot",
        "validation_url": "https://maharera.mahaonline.gov.in/",
        "google_maps_query": "Hiranandani Fortune City Panvel"
    },
    {
        "id": "plot_chn_01",
        "name": "TVS Emerald Hamlet",
        "builder_name": "TVS Emerald",
        "city_id": "chennai",
        "location": "Karapakkam, OMR, Chennai",
        "state": "Tamil Nadu",
        "lat": 12.9150,
        "lng": 80.2350,
        "plot_sizes_sqft": "1,200 - 2,400 sqft",
        "price_per_sqft": 6500,
        "total_price_lakhs": 78.0,
        "elevation_m": 8,
        "approval_authority": "CMDA / TN-RERA Approved",
        "drainage_percolation": "Engineered storm drains connecting to Buckingham canal outfall.",
        "flood_risk_tag": "🟡 Moderate Monsoon Caution",
        "avoidance_score": 68,
        "verdict": "🟡 Watchlist (Monsoon Caution)",
        "validation_url": "https://www.rera.tn.gov.in/",
        "google_maps_query": "TVS Emerald Hamlet Karapakkam Chennai"
    },
    {
        "id": "plot_del_01",
        "name": "DLF Alameda",
        "builder_name": "DLF Limited",
        "city_id": "delhi_ncr",
        "location": "Sector 73, Gurugram (Southern Peripheral Rd)",
        "state": "Haryana",
        "lat": 28.4120,
        "lng": 77.0250,
        "plot_sizes_sqft": "2,700 - 9,000 sqft",
        "price_per_sqft": 22000,
        "total_price_lakhs": 594.0,
        "elevation_m": 228,
        "approval_authority": "DTCP Haryana / HRERA Approved",
        "drainage_percolation": "Underground stormwater network with 24x7 security and private power backup.",
        "flood_risk_tag": "🟢 Zero Waterlogging History",
        "avoidance_score": 94,
        "verdict": "🟢 Prime Resilient Plot",
        "validation_url": "https://haryanarera.gov.in/",
        "google_maps_query": "DLF Alameda Sector 73 Gurugram"
    },
    {
        "id": "plot_hyd_01",
        "name": "My Home Ankura",
        "builder_name": "My Home Group",
        "city_id": "hyderabad",
        "location": "Tellapur, West Hyderabad",
        "state": "Telangana",
        "lat": 17.4720,
        "lng": 78.2680,
        "plot_sizes_sqft": "2,400 - 4,500 sqft",
        "price_per_sqft": 10500,
        "total_price_lakhs": 252.0,
        "elevation_m": 542,
        "approval_authority": "HMDA / TS-RERA Approved",
        "drainage_percolation": "Rocky basalt foundation with dedicated internal rainwater recharge pits.",
        "flood_risk_tag": "🟢 Zero Water Inundation",
        "avoidance_score": 93,
        "verdict": "🟢 Prime Resilient Plot",
        "validation_url": "https://rera.telangana.gov.in/",
        "google_maps_query": "My Home Ankura Tellapur Hyderabad"
    },
    {
        "id": "plot_vns_01",
        "name": "Eldeco Shaurya Plots",
        "builder_name": "Eldeco Group",
        "city_id": "varanasi_100km",
        "location": "Airport Road / Shivpur Corridor, Varanasi",
        "state": "Uttar Pradesh",
        "lat": 25.3720,
        "lng": 82.9550,
        "plot_sizes_sqft": "1,500 - 3,200 sqft",
        "price_per_sqft": 4800,
        "total_price_lakhs": 72.0,
        "elevation_m": 84,
        "approval_authority": "Varanasi Development Authority (VDA) / UP-RERA",
        "drainage_percolation": "Elevated alluvial plain completely outside Ganga-Varuna flood buffer.",
        "flood_risk_tag": "🟢 Zero Flood History (High Ridge)",
        "avoidance_score": 95,
        "verdict": "🟢 Prime Resilient Plot",
        "validation_url": "https://up-rera.in/",
        "google_maps_query": "Eldeco Shaurya Varanasi"
    },
    {
        "id": "plot_vns_02",
        "name": "Sangam Vihar Gated Enclave",
        "builder_name": "Sangam Infratech",
        "city_id": "varanasi_100km",
        "location": "Civil Lines Extension, Prayagraj",
        "state": "Uttar Pradesh",
        "lat": 25.4600,
        "lng": 81.8220,
        "plot_sizes_sqft": "1,800 - 3,600 sqft",
        "price_per_sqft": 5500,
        "total_price_lakhs": 99.0,
        "elevation_m": 94,
        "approval_authority": "Prayagraj Development Authority (PDA) Approved",
        "drainage_percolation": "Elevated colonial grid ridge with underground drainage connection.",
        "flood_risk_tag": "🟢 Immune to Sangam Flood",
        "avoidance_score": 93,
        "verdict": "🟢 Prime Resilient Plot",
        "validation_url": "https://up-rera.in/",
        "google_maps_query": "Civil Lines Prayagraj Plots"
    }
]

# ==========================================
# 6. AVOIDANCE ZONES DATASET (12 Pockets)
# ==========================================
avoidance_zones = [
    {
        "id": "avz_mum_01",
        "name": "Andheri Subway & S.V. Road Lowlands",
        "city": "Mumbai",
        "state": "Maharashtra",
        "lat": 19.1197,
        "lng": 72.8464,
        "severity": "CRITICAL AVOIDANCE",
        "elevation_delta_m": "-4.2m below railway tracks",
        "historical_closures_annual": "12 to 18 full closures per monsoon season",
        "root_cause": "Tidal backflow from Mogara Nullah during high sea tide (>4.5m) coinciding with rainfall >40mm/hr.",
        "mitigation_status": "BMC installed 5 dewatering pumps (6000 m3/hr capacity), but subway remains vulnerable to extreme cloudbursts.",
        "real_estate_impact": "Severe ground-floor property dampness, subterranean car park flooding, 1.5 - 2 hour traffic diversions.",
        "citation": "Moneycontrol / BMC Disaster Management Cell monsoon logs (2018-2025)."
    },
    {
        "id": "avz_mum_02",
        "name": "Kurla & Sion Chunabhatti Mithi River Basin",
        "city": "Mumbai",
        "state": "Maharashtra",
        "lat": 19.0657,
        "lng": 72.8794,
        "severity": "CRITICAL AVOIDANCE",
        "elevation_delta_m": "-6.0m reclaimed wetland basin",
        "historical_closures_annual": "Central Railway tracks submerged 8-12 days per monsoon",
        "root_cause": "Mithi river bottlenecks under CST Road Bridge and Kurla railway culverts. Encroached river channel.",
        "mitigation_status": "BRIMSTOWAD widening partially done; holding pond near Chunabhatti proposed.",
        "real_estate_impact": "Property value stagnation, structural dampness, severe vehicle damage, uninsurable basements.",
        "citation": "BRIMSTOWAD High Powered Committee Report & IIT Bombay Urban Flood Study."
    },
    {
        "id": "avz_chn_01",
        "name": "Velachery Lakebed Inundation Zone",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "lat": 12.9750,
        "lng": 80.2206,
        "severity": "CRITICAL AVOIDANCE",
        "elevation_delta_m": "-5.5m below surrounding Guindy ridge",
        "historical_closures_annual": "Flooded in 2015, 2021, 2023 (Cyclone Michaung), 2024",
        "root_cause": "Construction on natural Velachery lakebed and secondary drainage channels to Pallikaranai marsh.",
        "mitigation_status": "Greater Chennai Corporation widened Vijayanagar culvert, but secondary streets remain submerged for days.",
        "real_estate_impact": "Boats deployed for rescue; residents park cars on bypass flyovers during cyclone alerts; high rental discount in winter.",
        "citation": "Urban-Flood-Risk-Mapping (RushilGargash08) & TNGIS Velachery Drainage Vulnerability Map."
    },
    {
        "id": "avz_chn_02",
        "name": "Pallikaranai Marsh Encroachment Fringe",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "lat": 12.9350,
        "lng": 80.2150,
        "severity": "CRITICAL AVOIDANCE",
        "elevation_delta_m": "-7.0m lowest natural sink of South Chennai",
        "historical_closures_annual": "Multi-week inundation after every cyclone",
        "root_cause": "Marshland area shrunk from 5,000 hectares to under 600 hectares due to unauthorized colonisation and dumping.",
        "mitigation_status": "Madras High Court declared wetland buffer zone; strict enforcement against unauthorized building approvals.",
        "real_estate_impact": "Legal title scrutiny, high groundwater salinity (>850 ppm TDS), severe basement flooding.",
        "citation": "National Green Tribunal (NGT) Principal Bench wetland demarcation order."
    },
    {
        "id": "avz_blr_01",
        "name": "Rainbow Drive Layout & Sarjapur Road SWD Choke",
        "city": "Bengaluru",
        "state": "Karnataka",
        "lat": 12.9080,
        "lng": 77.6880,
        "severity": "CRITICAL AVOIDANCE",
        "elevation_delta_m": "-8.5m natural valley depression",
        "historical_closures_annual": "Tractors deployed for evacuation 3 times (2022-2024)",
        "root_cause": "Layout built across Halanayakanahalli lake surplus storm water drain; upstream lake overflows directly through entrance arch.",
        "mitigation_status": "BBMP reconstructed culvert across Sarjapur road, but internal villa basements remain in low-lying depression.",
        "real_estate_impact": "Severe property price correction, high legal disputes, multi-lakh monsoon drainage pumping costs.",
        "citation": "India Flood Inventory (IIT Delhi HydroSense) & BBMP Storm Water Drain Audit 2023."
    },
    {
        "id": "avz_blr_02",
        "name": "Bellandur EcoSpace Underpass & Service Road",
        "city": "Bengaluru",
        "state": "Karnataka",
        "lat": 12.9260,
        "lng": 77.6830,
        "severity": "HIGH MONSOON AVOIDANCE",
        "elevation_delta_m": "-6.0m below main carriageway",
        "historical_closures_annual": "Flooded 4-6 times every year",
        "root_cause": "K&C valley stormwater drain narrows under the Outer Ring Road service road; siltation causes reverse overflow.",
        "mitigation_status": "BBMP built elevated retaining walls and high-power diesel pumps.",
        "real_estate_impact": "1.5 - 3 hour commute delays across entire Outer Ring Road tech corridor during 50mm+ rainfall.",
        "citation": "blr-water-log (diagram-chasing) & Bangalore Traffic Wasted Time Predictor (parthtiwari-dev)."
    },
    {
        "id": "avz_del_01",
        "name": "Yamuna Floodplain Settlements & Mayur Vihar Lowlands",
        "city": "Delhi-NCR",
        "state": "Delhi / UP",
        "lat": 28.5980,
        "lng": 77.2950,
        "severity": "CRITICAL AVOIDANCE",
        "elevation_delta_m": "-2.5m below Yamuna High Flood Level (208.66m)",
        "historical_closures_annual": "Evacuated in 2023 record floods (Yamuna reached 208.66m)",
        "root_cause": "Unauthorized construction within active river floodplains and backflow into Shahdara drain.",
        "mitigation_status": "Delhi IFCD reinforced ITO and Mayur Vihar regulator gates.",
        "real_estate_impact": "High flood hazard, structural inundation up to ground floor ceiling during release from Hathnikund Barrage.",
        "citation": "Central Water Commission (CWC) Delhi Yamuna Flood Analysis Report 2023."
    },
    {
        "id": "avz_del_02",
        "name": "Barapullah Phase-III 90-Degree Traffic Choke Point",
        "city": "Delhi-NCR",
        "state": "Delhi",
        "lat": 28.5880,
        "lng": 77.2550,
        "severity": "CHRONIC TRAFFIC AVOIDANCE",
        "elevation_delta_m": "Elevated Flyover Abutment",
        "historical_closures_annual": "Daily peak hour speed drops to <5 km/h",
        "root_cause": "Flawed civil engineering design: multi-lane expressway merges abruptly into a 90-degree narrow exit lane at Mayur Vihar/Noida border.",
        "mitigation_status": "PWD Delhi planning redesign of cloverleaf loop; land acquisition pending.",
        "real_estate_impact": "45-60 minutes wasted daily per commuter connecting South Delhi to East Delhi/Noida.",
        "citation": "Hindustan Times: Barapullah Phase-III Design Flaw and Traffic Bottleneck Exposure."
    },
    {
        "id": "avz_hyd_01",
        "name": "Musi River Moosarambagh & Chaderghat Lowlands",
        "city": "Hyderabad",
        "state": "Telangana",
        "lat": 17.3750,
        "lng": 78.5050,
        "severity": "CRITICAL AVOIDANCE",
        "elevation_delta_m": "-25m lowest regional valley floor",
        "historical_closures_annual": "Moosarambagh causeway submerged 3-5 times annually",
        "root_cause": "Hydraulic release from Osmansagar and Himayatsagar dams directly floods low-lying riverbed colonies.",
        "mitigation_status": "Telangana Govt proposed Musi Riverfront Development Project; high-level bridge under construction.",
        "real_estate_impact": "Colonies evacuated during monsoon; poor sanitation, structural damage, zero institutional home loan approvals.",
        "citation": "GHMC Disaster Response & CWC Musi River Basin Flood Study."
    },
    {
        "id": "avz_vns_01",
        "name": "Prayagraj Baghada & Salori Sangam Confluence",
        "city": "Prayagraj",
        "state": "Uttar Pradesh",
        "lat": 25.4650,
        "lng": 81.8700,
        "severity": "CRITICAL AVOIDANCE",
        "elevation_delta_m": "-4.0m below Sangam High Flood Level (86.40m)",
        "historical_closures_annual": "Flooded every August-September; 10,000+ students evacuated",
        "root_cause": "Dual backwater surge: swollen Yamuna blocks Ganga outflow, causing water to pool into low-lying natural bowl colonies.",
        "mitigation_status": "Salori pumping station upgraded, but ineffective when river levels cross 84.73m danger mark.",
        "real_estate_impact": "Extreme seasonal flood avoidance; student lodges submerge up to 1st floor; heavy mud and epidemic risk.",
        "citation": "IIT Gandhinagar India Flood Atlas (wcl-iitgn) historical Doab inundation series 1901-2020."
    },
    {
        "id": "avz_vns_02",
        "name": "Varanasi Ganga-Varuna Confluence (Sarai Mohana & Konia)",
        "city": "Varanasi",
        "state": "Uttar Pradesh",
        "lat": 25.3340,
        "lng": 83.0380,
        "severity": "CRITICAL AVOIDANCE",
        "elevation_delta_m": "-2.5m below Ganga High Flood Level (73.90m)",
        "historical_closures_annual": "Flooded 7 out of last 10 monsoons",
        "root_cause": "Ganga backwaters push up the Varuna tributary for 8 km, inundating all low-lying riverbank developments.",
        "mitigation_status": "Varuna corridor embankment retaining wall partially built under Namami Gange.",
        "real_estate_impact": "Houses inundated up to 6-8 feet; heavy silt deposition; strict avoidance for residential home purchases.",
        "citation": "Varanasi City Region Flood Risk Study (ResearchGate) 1-meter DEM Varuna floodplain survey."
    },
    {
        "id": "avz_vns_03",
        "name": "Jaunpur Gomti River Shahi Bridge Hydraulic Choke",
        "city": "Jaunpur",
        "state": "Uttar Pradesh",
        "lat": 25.7460,
        "lng": 82.6840,
        "severity": "DUAL FLOOD & TRAFFIC AVOIDANCE",
        "elevation_delta_m": "-3.0m below Gomti river embankment",
        "historical_closures_annual": "Flooded during intense Gomti catchment downpours",
        "root_cause": "Narrow stone arches of 16th-century Mughal Shahi Bridge obstruct swollen river flow and create 2-hour road bottlenecks.",
        "mitigation_status": "New bypass bridge operational, but inner city market streets remain bottlenecked.",
        "real_estate_impact": "High flood hazard for riverbank properties within 400m; severe commercial gridlock.",
        "citation": "IIT Delhi HydroSense (hydrosenselab) Gomti basin flood event catalog."
    }
]

# ==========================================
# 7. USER PREFERENCES DATASET
# ==========================================
user_preferences = {
    "selected_city": "bengaluru",
    "budget_purchase_max_cr": 3.5,
    "budget_rental_max_pm": 80000,
    "max_acceptable_delay_index": 2.2,
    "min_elevation_m": 15,
    "avoidance_threshold_score": 50,
    "preferred_builders": ["Prestige Group", "Sobha Limited", "Godrej Properties", "Oberoi Realty"],
    "require_piped_water": True,
    "exclude_flood_risk_categories": ["🔴 Severe Waterlogging (Lake Valley Depression)", "🔴 Severe Waterlogging (Chronic Subway Inundation)"]
}

# Write JSON files
with open(os.path.join(DATA_DIR, "properties.json"), "w", encoding="utf-8") as f:
    json.dump(properties, f, indent=2, ensure_ascii=False)

with open(os.path.join(DATA_DIR, "gated_plots.json"), "w", encoding="utf-8") as f:
    json.dump(gated_plots, f, indent=2, ensure_ascii=False)

with open(os.path.join(DATA_DIR, "avoidance_zones.json"), "w", encoding="utf-8") as f:
    json.dump(avoidance_zones, f, indent=2, ensure_ascii=False)

with open(os.path.join(DATA_DIR, "user_preferences.json"), "w", encoding="utf-8") as f:
    json.dump(user_preferences, f, indent=2, ensure_ascii=False)

print("Generated properties.json, gated_plots.json, avoidance_zones.json, and user_preferences.json successfully.")
