"""
Comprehensive Property, Rental, Plotted & Master Plan Data Generator
Creates:
1. data/properties.json (18 purchase & investment properties across 6 cities)
2. data/rental_properties.json (18 rental benchmark properties across 6 cities)
3. data/gated_plots.json (18 gated community plots across 6 cities)
4. data/govt_master_plans.json (Government infrastructure growth catalysts & timelines across all 6 regions)
"""

import json
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BASE_DIR, "data")
os.makedirs(DATA_DIR, exist_ok=True)

# ==========================================
# 1. PURCHASE & INVESTMENT INVENTORIES (18 Properties: 3 per City)
# ==========================================
properties = [
    # --- BENGALURU ---
    {
        "id": "prop_blr_1",
        "name": "Sobha Neopolis",
        "builder": "Sobha Limited",
        "builder_tier": "Tier 1 Premier National",
        "city_id": "bengaluru",
        "city_name": "Bengaluru",
        "micro_market": "Panathur - Balagere Road",
        "lat": 12.9348,
        "lng": 77.7120,
        "bhk": "3 BHK Luxury",
        "avg_sqft": 1820,
        "price_per_sqft": 14200,
        "total_price_cr": 2.58,
        "monthly_maintenance_inr": 8500,
        "upfront_cash_required_lakhs": 61.5,
        "total_ownership_cost_cr": 2.76,
        "investment_score": 94.8,
        "growth_probability_pct": 92,
        "govt_master_plan_catalyst": "Namma Metro Blue Line ORR Phase 2A (Kadubeesanahalli Stn 2026) + Balagere-Varthur 100ft CDP Road expansion",
        "road_distance_to_key_landmark_km": 14.8,
        "road_distance_to_school_benchmark_km": 1.4,
        "school_benchmark_name": "New Horizon Gurukul",
        "elevation_m": 884,
        "flood_resilience_tag": "High Plinth (Elevated Natural Ridge)",
        "water_infrastructure": {
            "piped_connection": "BWSSB Stage V Sanctioned",
            "has_stp": True,
            "has_water_softener": True,
            "has_water_meter": True,
            "has_gas_pipeline": True,
            "tanker_reliance_index": 2.5
        },
        "nearby_cbse_schools": [
            {"name": "New Horizon Gurukul", "distance_km": 1.4, "rating": 4.6, "annual_fees_class_1_to_5": "₹1.45L - ₹1.70L", "annual_fees_class_6_to_10": "₹1.75L - ₹2.05L", "annual_fees_class_11_to_12": "₹1.90L - ₹2.25L"},
            {"name": "Gear Innovative International School", "distance_km": 2.8, "rating": 4.4, "annual_fees_class_1_to_5": "₹1.50L - ₹1.80L", "annual_fees_class_6_to_10": "₹1.80L - ₹2.15L", "annual_fees_class_11_to_12": "₹2.00L - ₹2.35L"}
        ],
        "google_maps_query": "Sobha Neopolis Panathur Bangalore",
        "rera_url": "https://rera.karnataka.gov.in/"
    },
    {
        "id": "prop_blr_2",
        "name": "Prestige Falcon City",
        "builder": "Prestige Group",
        "builder_tier": "Tier 1 Premier National",
        "city_id": "bengaluru",
        "city_name": "Bengaluru",
        "micro_market": "Kanakapura Road",
        "lat": 12.8930,
        "lng": 77.5585,
        "bhk": "3 BHK Premium",
        "avg_sqft": 1780,
        "price_per_sqft": 12800,
        "total_price_cr": 2.28,
        "monthly_maintenance_inr": 7800,
        "upfront_cash_required_lakhs": 54.2,
        "total_ownership_cost_cr": 2.45,
        "investment_score": 93.2,
        "growth_probability_pct": 90,
        "govt_master_plan_catalyst": "Namma Metro Green Line directly at Konanakunte Cross + Forum Mall integration + NICE Peripheral Expressway",
        "road_distance_to_key_landmark_km": 11.2,
        "road_distance_to_school_benchmark_km": 18.5,
        "school_benchmark_name": "Kumaran Children's Home (CBSE)",
        "elevation_m": 912,
        "flood_resilience_tag": "Zero Inundation (High Table-land)",
        "water_infrastructure": {
            "piped_connection": "BWSSB Piped Active",
            "has_stp": True,
            "has_water_softener": True,
            "has_water_meter": True,
            "has_gas_pipeline": True,
            "tanker_reliance_index": 0.8
        },
        "nearby_cbse_schools": [
            {"name": "The Valley School (KFI)", "distance_km": 4.2, "rating": 4.8, "annual_fees_class_1_to_5": "₹1.80L - ₹2.20L", "annual_fees_class_6_to_10": "₹2.20L - ₹2.60L", "annual_fees_class_11_to_12": "₹2.50L - ₹2.90L"}
        ],
        "google_maps_query": "Prestige Falcon City Kanakapura Road Bangalore",
        "rera_url": "https://rera.karnataka.gov.in/"
    },
    {
        "id": "prop_blr_3",
        "name": "Brigade Cornerstone Utopia",
        "builder": "Brigade Group",
        "builder_tier": "Tier 1 Premier National",
        "city_id": "bengaluru",
        "city_name": "Bengaluru",
        "micro_market": "Varthur - Whitefield",
        "lat": 12.9515,
        "lng": 77.7280,
        "bhk": "3 BHK Smart Luxury",
        "avg_sqft": 1640,
        "price_per_sqft": 11900,
        "total_price_cr": 1.95,
        "monthly_maintenance_inr": 6900,
        "upfront_cash_required_lakhs": 47.0,
        "total_ownership_cost_cr": 2.10,
        "investment_score": 92.4,
        "growth_probability_pct": 89,
        "govt_master_plan_catalyst": "Comprehensive Varthur Lake rejuvenation + 6-lane Varthur-Sarjapur bypass arterial corridor",
        "road_distance_to_key_landmark_km": 17.5,
        "road_distance_to_school_benchmark_km": 4.5,
        "school_benchmark_name": "New Horizon Gurukul",
        "elevation_m": 885,
        "flood_resilience_tag": "Engineered SWD with High Berm Buffer",
        "water_infrastructure": {
            "piped_connection": "BWSSB Stage V Dual Connection",
            "has_stp": True,
            "has_water_softener": True,
            "has_water_meter": True,
            "has_gas_pipeline": True,
            "tanker_reliance_index": 3.0
        },
        "nearby_cbse_schools": [
            {"name": "Greenwood High International School", "distance_km": 4.1, "rating": 4.7, "annual_fees_class_1_to_5": "₹2.20L - ₹2.80L", "annual_fees_class_6_to_10": "₹2.90L - ₹3.60L", "annual_fees_class_11_to_12": "₹3.40L - ₹4.20L"}
        ],
        "google_maps_query": "Brigade Cornerstone Utopia Varthur Bangalore",
        "rera_url": "https://rera.karnataka.gov.in/"
    },

    # --- MUMBAI & MMR ---
    {
        "id": "prop_mum_1",
        "name": "Oberoi Sky City",
        "builder": "Oberoi Realty",
        "builder_tier": "Tier 1 Premier National",
        "city_id": "mumbai_mmr",
        "city_name": "Mumbai & MMR",
        "micro_market": "Borivali East - WEH",
        "lat": 19.2230,
        "lng": 72.8640,
        "bhk": "3 BHK Grande",
        "avg_sqft": 1420,
        "price_per_sqft": 26800,
        "total_price_cr": 3.81,
        "monthly_maintenance_inr": 12500,
        "upfront_cash_required_lakhs": 92.0,
        "total_ownership_cost_cr": 4.10,
        "investment_score": 96.2,
        "growth_probability_pct": 95,
        "govt_master_plan_catalyst": "Direct Metro Line 7 dedicated skywalk + Goregaon-Mulund Link Road (GMLR) twin tunnels + Coastal Road extension",
        "road_distance_to_key_landmark_km": 28.0,
        "road_distance_to_school_benchmark_km": 17.5,
        "school_benchmark_name": "Dhirubhai Ambani Intl School",
        "elevation_m": 38,
        "flood_resilience_tag": "Zero Inundation (Natural Granitic Base)",
        "water_infrastructure": {
            "piped_connection": "BMC 24x7 Piped Dedicated",
            "has_stp": True,
            "has_water_softener": True,
            "has_water_meter": True,
            "has_gas_pipeline": True,
            "tanker_reliance_index": 0.2
        },
        "nearby_cbse_schools": [
            {"name": "Oberoi International School", "distance_km": 5.4, "rating": 4.9, "annual_fees_class_1_to_5": "₹3.50L - ₹4.50L", "annual_fees_class_6_to_10": "₹4.50L - ₹5.80L", "annual_fees_class_11_to_12": "₹5.50L - ₹7.00L"}
        ],
        "google_maps_query": "Oberoi Sky City Borivali East Mumbai",
        "rera_url": "https://maharera.mahaonline.gov.in/"
    },
    {
        "id": "prop_mum_2",
        "name": "L&T Seawoods Residences",
        "builder": "L&T Realty",
        "builder_tier": "Tier 1 Premier National",
        "city_id": "mumbai_mmr",
        "city_name": "Mumbai & MMR",
        "micro_market": "Seawoods - Navi Mumbai",
        "lat": 19.0180,
        "lng": 73.0160,
        "bhk": "3 BHK Transit-Oriented",
        "avg_sqft": 1350,
        "price_per_sqft": 21500,
        "total_price_cr": 2.90,
        "monthly_maintenance_inr": 9200,
        "upfront_cash_required_lakhs": 70.0,
        "total_ownership_cost_cr": 3.12,
        "investment_score": 94.5,
        "growth_probability_pct": 93,
        "govt_master_plan_catalyst": "Navi Mumbai International Airport (NMIA 2025 operational) + Atal Setu MTHL connection (20 min to South Mumbai)",
        "road_distance_to_key_landmark_km": 24.5,
        "road_distance_to_school_benchmark_km": 1.8,
        "school_benchmark_name": "DPS Navi Mumbai",
        "elevation_m": 12,
        "flood_resilience_tag": "Engineered CIDCO Polder Drainage (No waterlogging)",
        "water_infrastructure": {
            "piped_connection": "NMMC Morbe Dam 24x7 Piped",
            "has_stp": True,
            "has_water_softener": True,
            "has_water_meter": True,
            "has_gas_pipeline": True,
            "tanker_reliance_index": 0.4
        },
        "nearby_cbse_schools": [
            {"name": "Delhi Public School (Nerul)", "distance_km": 1.8, "rating": 4.8, "annual_fees_class_1_to_5": "₹1.40L - ₹1.75L", "annual_fees_class_6_to_10": "₹1.75L - ₹2.10L", "annual_fees_class_11_to_12": "₹1.95L - ₹2.35L"}
        ],
        "google_maps_query": "L&T Seawoods Residences Navi Mumbai",
        "rera_url": "https://maharera.mahaonline.gov.in/"
    },
    {
        "id": "prop_mum_3",
        "name": "Godrej The Trees",
        "builder": "Godrej Properties",
        "builder_tier": "Tier 1 Premier National",
        "city_id": "mumbai_mmr",
        "city_name": "Mumbai & MMR",
        "micro_market": "Vikhroli East - Eastern Express Highway",
        "lat": 19.1020,
        "lng": 72.9280,
        "bhk": "3 BHK Sustainable Suite",
        "avg_sqft": 1490,
        "price_per_sqft": 25500,
        "total_price_cr": 3.80,
        "monthly_maintenance_inr": 11000,
        "upfront_cash_required_lakhs": 90.0,
        "total_ownership_cost_cr": 4.08,
        "investment_score": 93.9,
        "growth_probability_pct": 92,
        "govt_master_plan_catalyst": "Mumbai Metro Line 4 (Wadala-Kasarvadavali) + Eastern Freeway extension to Thane",
        "road_distance_to_key_landmark_km": 16.5,
        "road_distance_to_school_benchmark_km": 11.0,
        "school_benchmark_name": "Dhirubhai Ambani Intl School",
        "elevation_m": 16,
        "flood_resilience_tag": "Zero Inundation (Protected Mangrove Buffer Zone)",
        "water_infrastructure": {
            "piped_connection": "BMC Piped 24x7 Active",
            "has_stp": True,
            "has_water_softener": True,
            "has_water_meter": True,
            "has_gas_pipeline": True,
            "tanker_reliance_index": 0.3
        },
        "nearby_cbse_schools": [
            {"name": "Bombay Scottish School (Powai)", "distance_km": 4.5, "rating": 4.8, "annual_fees_class_1_to_5": "₹1.90L - ₹2.50L", "annual_fees_class_6_to_10": "₹2.50L - ₹3.20L", "annual_fees_class_11_to_12": "₹2.90L - ₹3.60L"}
        ],
        "google_maps_query": "Godrej The Trees Vikhroli Mumbai",
        "rera_url": "https://maharera.mahaonline.gov.in/"
    },

    # --- CHENNAI ---
    {
        "id": "prop_chn_1",
        "name": "Purva Somerset House",
        "builder": "Puravankara Limited",
        "builder_tier": "Tier 1 Premier National",
        "city_id": "chennai",
        "city_name": "Chennai",
        "micro_market": "Guindy - Race Course",
        "lat": 13.0080,
        "lng": 80.2120,
        "bhk": "3 BHK Ultra-Luxury",
        "avg_sqft": 1950,
        "price_per_sqft": 16200,
        "total_price_cr": 3.16,
        "monthly_maintenance_inr": 9800,
        "upfront_cash_required_lakhs": 76.5,
        "total_ownership_cost_cr": 3.39,
        "investment_score": 95.1,
        "growth_probability_pct": 93,
        "govt_master_plan_catalyst": "Chennai Metro Corridor 3 & Corridor 5 multi-modal interchange at Kathipara + Anna Salai flyover link",
        "road_distance_to_key_landmark_km": 9.5,
        "road_distance_to_school_benchmark_km": 4.5,
        "school_benchmark_name": "Sishya School",
        "elevation_m": 18,
        "flood_resilience_tag": "Elevated Geological Ridge (+12m above tidal surge)",
        "water_infrastructure": {
            "piped_connection": "CMWSSB 24x7 Piped Line",
            "has_stp": True,
            "has_water_softener": True,
            "has_water_meter": True,
            "has_gas_pipeline": True,
            "tanker_reliance_index": 1.2
        },
        "nearby_cbse_schools": [
            {"name": "Sishya School (Adyar)", "distance_km": 4.5, "rating": 4.9, "annual_fees_class_1_to_5": "₹1.60L - ₹2.10L", "annual_fees_class_6_to_10": "₹2.10L - ₹2.60L", "annual_fees_class_11_to_12": "₹2.40L - ₹2.90L"}
        ],
        "google_maps_query": "Purva Somerset House Guindy Chennai",
        "rera_url": "https://www.rera.tn.gov.in/"
    },
    {
        "id": "prop_chn_2",
        "name": "Brigade Residences at WTC",
        "builder": "Brigade Group",
        "builder_tier": "Tier 1 Premier National",
        "city_id": "chennai",
        "city_name": "Chennai",
        "micro_market": "Perungudi - OMR IT Corridor",
        "lat": 12.9650,
        "lng": 80.2450,
        "bhk": "3 BHK Corporate Suite",
        "avg_sqft": 1780,
        "price_per_sqft": 14500,
        "total_price_cr": 2.58,
        "monthly_maintenance_inr": 8900,
        "upfront_cash_required_lakhs": 62.0,
        "total_ownership_cost_cr": 2.76,
        "investment_score": 93.6,
        "growth_probability_pct": 91,
        "govt_master_plan_catalyst": "Chennai Metro Phase 2 OMR line along corridor + Perungudi tidal storm canal redesign",
        "road_distance_to_key_landmark_km": 14.0,
        "road_distance_to_school_benchmark_km": 4.1,
        "school_benchmark_name": "The School - KFI",
        "elevation_m": 7.5,
        "flood_resilience_tag": "High Raised Plinth (+1.8m above OMR road grade)",
        "water_infrastructure": {
            "piped_connection": "CMWSSB Piped + Dual Membrane STP",
            "has_stp": True,
            "has_water_softener": True,
            "has_water_meter": True,
            "has_gas_pipeline": True,
            "tanker_reliance_index": 2.8
        },
        "nearby_cbse_schools": [
            {"name": "The School - KFI", "distance_km": 4.1, "rating": 4.8, "annual_fees_class_1_to_5": "₹1.50L - ₹1.90L", "annual_fees_class_6_to_10": "₹1.90L - ₹2.40L", "annual_fees_class_11_to_12": "₹2.20L - ₹2.70L"}
        ],
        "google_maps_query": "Brigade Residences World Trade Center Perungudi Chennai",
        "rera_url": "https://www.rera.tn.gov.in/"
    },
    {
        "id": "prop_chn_3",
        "name": "Appaswamy Trellis",
        "builder": "Appaswamy Real Estates",
        "builder_tier": "Tier 1 Regional Champion",
        "city_id": "chennai",
        "city_name": "Chennai",
        "micro_market": "Vadapalani - Inner Ring Road",
        "lat": 13.0510,
        "lng": 80.2080,
        "bhk": "3 BHK Metro Core",
        "avg_sqft": 1520,
        "price_per_sqft": 12800,
        "total_price_cr": 1.95,
        "monthly_maintenance_inr": 6200,
        "upfront_cash_required_lakhs": 48.0,
        "total_ownership_cost_cr": 2.10,
        "investment_score": 92.8,
        "growth_probability_pct": 89,
        "govt_master_plan_catalyst": "Chennai Metro Green & Blue Line connectivity + 100ft Inner Ring Road flyover network",
        "road_distance_to_key_landmark_km": 7.2,
        "road_distance_to_school_benchmark_km": 5.0,
        "school_benchmark_name": "DAV Senior Secondary",
        "elevation_m": 15,
        "flood_resilience_tag": "Zero Inundation (Natural High Alluvial Ridge)",
        "water_infrastructure": {
            "piped_connection": "CMWSSB Dedicated Active",
            "has_stp": True,
            "has_water_softener": True,
            "has_water_meter": True,
            "has_gas_pipeline": True,
            "tanker_reliance_index": 1.0
        },
        "nearby_cbse_schools": [
            {"name": "DAV Boys Senior Secondary School", "distance_km": 4.8, "rating": 4.8, "annual_fees_class_1_to_5": "₹90K - ₹1.25L", "annual_fees_class_6_to_10": "₹1.20L - ₹1.55L", "annual_fees_class_11_to_12": "₹1.45L - ₹1.80L"}
        ],
        "google_maps_query": "Appaswamy Trellis Vadapalani Chennai",
        "rera_url": "https://www.rera.tn.gov.in/"
    },

    # --- DELHI-NCR ---
    {
        "id": "prop_del_1",
        "name": "DLF The Crest",
        "builder": "DLF Limited",
        "builder_tier": "Tier 1 Premier National",
        "city_id": "delhi_ncr",
        "city_name": "Delhi-NCR",
        "micro_market": "Golf Course Road - Sec 54 Gurugram",
        "lat": 28.4450,
        "lng": 77.1060,
        "bhk": "3 BHK Luxury",
        "avg_sqft": 2680,
        "price_per_sqft": 24500,
        "total_price_cr": 6.57,
        "monthly_maintenance_inr": 18000,
        "upfront_cash_required_lakhs": 155.0,
        "total_ownership_cost_cr": 7.05,
        "investment_score": 97.4,
        "growth_probability_pct": 96,
        "govt_master_plan_catalyst": "Gurugram Rapid Metro line station integration + 16-lane signal-free expressway + Direct Aravali green corridor",
        "road_distance_to_key_landmark_km": 26.0,
        "road_distance_to_school_benchmark_km": 1.8,
        "school_benchmark_name": "The Shri Ram School Aravali",
        "elevation_m": 235,
        "flood_resilience_tag": "Zero Inundation (Elevated Foothills Slope)",
        "water_infrastructure": {
            "piped_connection": "GMDA Canal Piped Water Active",
            "has_stp": True,
            "has_water_softener": True,
            "has_water_meter": True,
            "has_gas_pipeline": True,
            "tanker_reliance_index": 0.3
        },
        "nearby_cbse_schools": [
            {"name": "The Shri Ram School (Aravali)", "distance_km": 1.8, "rating": 4.9, "annual_fees_class_1_to_5": "₹2.80L - ₹3.60L", "annual_fees_class_6_to_10": "₹3.60L - ₹4.50L", "annual_fees_class_11_to_12": "₹4.20L - ₹5.20L"}
        ],
        "google_maps_query": "DLF The Crest Golf Course Road Gurgaon",
        "rera_url": "https://haryanarera.gov.in/"
    },
    {
        "id": "prop_del_2",
        "name": "Eldeco Live Neoma",
        "builder": "Eldeco Group",
        "builder_tier": "Tier 1 Regional Champion (North)",
        "city_id": "delhi_ncr",
        "city_name": "Delhi-NCR",
        "micro_market": "Sector 150 - Noida Expressway",
        "lat": 28.4350,
        "lng": 77.4980,
        "bhk": "3 BHK Sports City",
        "avg_sqft": 1750,
        "price_per_sqft": 10800,
        "total_price_cr": 1.89,
        "monthly_maintenance_inr": 6500,
        "upfront_cash_required_lakhs": 46.0,
        "total_ownership_cost_cr": 2.03,
        "investment_score": 94.0,
        "growth_probability_pct": 94,
        "govt_master_plan_catalyst": "Noida International Airport Jewar (20 mins via Yamuna Exp) + Aqua Line Metro Extension + 80% designated green zone",
        "road_distance_to_key_landmark_km": 36.0,
        "road_distance_to_school_benchmark_km": 6.2,
        "school_benchmark_name": "Step by Step School",
        "elevation_m": 204,
        "flood_resilience_tag": "High Engineered Plinth (Outside Yamuna O-Zone)",
        "water_infrastructure": {
            "piped_connection": "Noida Authority Ganga Piped Line",
            "has_stp": True,
            "has_water_softener": True,
            "has_water_meter": True,
            "has_gas_pipeline": True,
            "tanker_reliance_index": 0.9
        },
        "nearby_cbse_schools": [
            {"name": "Step by Step School (Sector 132)", "distance_km": 6.2, "rating": 4.9, "annual_fees_class_1_to_5": "₹2.50L - ₹3.20L", "annual_fees_class_6_to_10": "₹3.20L - ₹3.90L", "annual_fees_class_11_to_12": "₹4.20L - ₹4.80L"}
        ],
        "google_maps_query": "Eldeco Live Neoma Sector 150 Noida",
        "rera_url": "https://up-rera.in/"
    },
    {
        "id": "prop_del_3",
        "name": "Godrej South Estate",
        "builder": "Godrej Properties",
        "builder_tier": "Tier 1 Premier National",
        "city_id": "delhi_ncr",
        "city_name": "Delhi-NCR",
        "micro_market": "Okhla Phase 1 - South Delhi",
        "lat": 28.5280,
        "lng": 77.2780,
        "bhk": "3 BHK Ultra Luxury",
        "avg_sqft": 2150,
        "price_per_sqft": 22500,
        "total_price_cr": 4.84,
        "monthly_maintenance_inr": 14000,
        "upfront_cash_required_lakhs": 115.0,
        "total_ownership_cost_cr": 5.20,
        "investment_score": 94.6,
        "growth_probability_pct": 93,
        "govt_master_plan_catalyst": "Delhi Metro Magenta & Violet Lines intersection + DDA Transit-Oriented Development (TOD) corridor",
        "road_distance_to_key_landmark_km": 14.2,
        "road_distance_to_school_benchmark_km": 5.8,
        "school_benchmark_name": "DPS R.K. Puram",
        "elevation_m": 218,
        "flood_resilience_tag": "Zero Inundation (High Ridge Flank)",
        "water_infrastructure": {
            "piped_connection": "Delhi Jal Board (DJB) Treated Water",
            "has_stp": True,
            "has_water_softener": True,
            "has_water_meter": True,
            "has_gas_pipeline": True,
            "tanker_reliance_index": 0.4
        },
        "nearby_cbse_schools": [
            {"name": "Delhi Public School (Mathura Road)", "distance_km": 6.8, "rating": 4.8, "annual_fees_class_1_to_5": "₹1.80L - ₹2.20L", "annual_fees_class_6_to_10": "₹2.20L - ₹2.60L", "annual_fees_class_11_to_12": "₹2.50L - ₹3.00L"}
        ],
        "google_maps_query": "Godrej South Estate Okhla Delhi",
        "rera_url": "https://delhirera.in/"
    },

    # --- HYDERABAD ---
    {
        "id": "prop_hyd_1",
        "name": "My Home Bhooja",
        "builder": "My Home Group",
        "builder_tier": "Tier 1 Regional Champion",
        "city_id": "hyderabad",
        "city_name": "Hyderabad",
        "micro_market": "HITECH City - Knowledge City",
        "lat": 17.4380,
        "lng": 78.3780,
        "bhk": "3 BHK Iconic Skyvilla",
        "avg_sqft": 2595,
        "price_per_sqft": 14800,
        "total_price_cr": 3.84,
        "monthly_maintenance_inr": 11500,
        "upfront_cash_required_lakhs": 91.0,
        "total_ownership_cost_cr": 4.12,
        "investment_score": 96.5,
        "growth_probability_pct": 95,
        "govt_master_plan_catalyst": "Hyderabad Metro Blue Line station walking distance + Inorbit Mall flyover + Bio-Diversity flyover network",
        "road_distance_to_key_landmark_km": 14.5,
        "road_distance_to_school_benchmark_km": 3.8,
        "school_benchmark_name": "Oakridge International School",
        "elevation_m": 582,
        "flood_resilience_tag": "Zero Inundation (High Granite Hillock)",
        "water_infrastructure": {
            "piped_connection": "HMWSSB Godavari Piped 24x7",
            "has_stp": True,
            "has_water_softener": True,
            "has_water_meter": True,
            "has_gas_pipeline": True,
            "tanker_reliance_index": 0.2
        },
        "nearby_cbse_schools": [
            {"name": "Oakridge International School", "distance_km": 3.8, "rating": 4.8, "annual_fees_class_1_to_5": "₹2.60L - ₹3.40L", "annual_fees_class_6_to_10": "₹3.40L - ₹4.30L", "annual_fees_class_11_to_12": "₹4.00L - ₹5.00L"}
        ],
        "google_maps_query": "My Home Bhooja Hitec City Hyderabad",
        "rera_url": "https://rera.telangana.gov.in/"
    },
    {
        "id": "prop_hyd_2",
        "name": "Aparna Sarovar Zenith",
        "builder": "Aparna Constructions",
        "builder_tier": "Tier 1 Regional Champion",
        "city_id": "hyderabad",
        "city_name": "Hyderabad",
        "micro_market": "Nallagandla - Gachibowli",
        "lat": 17.4720,
        "lng": 78.3180,
        "bhk": "3 BHK Gated Park",
        "avg_sqft": 1850,
        "price_per_sqft": 9800,
        "total_price_cr": 1.81,
        "monthly_maintenance_inr": 6800,
        "upfront_cash_required_lakhs": 44.0,
        "total_ownership_cost_cr": 1.95,
        "investment_score": 94.2,
        "growth_probability_pct": 92,
        "govt_master_plan_catalyst": "Tellapur-Nallagandla 100ft road to ORR Exit 2 + Citizen Hospital healthcare corridor",
        "road_distance_to_key_landmark_km": 19.0,
        "road_distance_to_school_benchmark_km": 2.2,
        "school_benchmark_name": "CHIREC International",
        "elevation_m": 560,
        "flood_resilience_tag": "Zero Inundation (High Rocky Ridge)",
        "water_infrastructure": {
            "piped_connection": "HMWSSB Krishna Piped Supply",
            "has_stp": True,
            "has_water_softener": True,
            "has_water_meter": True,
            "has_gas_pipeline": True,
            "tanker_reliance_index": 0.8
        },
        "nearby_cbse_schools": [
            {"name": "CHIREC International School", "distance_km": 2.2, "rating": 4.9, "annual_fees_class_1_to_5": "₹2.50L - ₹3.20L", "annual_fees_class_6_to_10": "₹3.20L - ₹4.00L", "annual_fees_class_11_to_12": "₹3.80L - ₹4.80L"}
        ],
        "google_maps_query": "Aparna Sarovar Zenith Nallagandla Hyderabad",
        "rera_url": "https://rera.telangana.gov.in/"
    },
    {
        "id": "prop_hyd_3",
        "name": "Prestige Clairemont",
        "builder": "Prestige Group",
        "builder_tier": "Tier 1 Premier National",
        "city_id": "hyderabad",
        "city_name": "Hyderabad",
        "micro_market": "Kokapet - Neopolis SEZ",
        "lat": 17.4040,
        "lng": 78.3320,
        "bhk": "3 BHK Premium High-Rise",
        "avg_sqft": 1980,
        "price_per_sqft": 11500,
        "total_price_cr": 2.28,
        "monthly_maintenance_inr": 7800,
        "upfront_cash_required_lakhs": 55.0,
        "total_ownership_cost_cr": 2.45,
        "investment_score": 95.4,
        "growth_probability_pct": 95,
        "govt_master_plan_catalyst": "Kokapet Neopolis SEZ 45m master roads + Direct ORR Trumpet Interchange + 100-acre Commercial CBD",
        "road_distance_to_key_landmark_km": 17.5,
        "road_distance_to_school_benchmark_km": 3.1,
        "school_benchmark_name": "Oakridge International School",
        "elevation_m": 578,
        "flood_resilience_tag": "Zero Inundation (Natural Granitic Slope)",
        "water_infrastructure": {
            "piped_connection": "HMWSSB Dedicated Line",
            "has_stp": True,
            "has_water_softener": True,
            "has_water_meter": True,
            "has_gas_pipeline": True,
            "tanker_reliance_index": 0.4
        },
        "nearby_cbse_schools": [
            {"name": "Oakridge International School", "distance_km": 3.1, "rating": 4.8, "annual_fees_class_1_to_5": "₹2.60L - ₹3.40L", "annual_fees_class_6_to_10": "₹3.40L - ₹4.30L", "annual_fees_class_11_to_12": "₹4.00L - ₹5.00L"}
        ],
        "google_maps_query": "Prestige Clairemont Kokapet Hyderabad",
        "rera_url": "https://rera.telangana.gov.in/"
    },

    # --- VARANASI & EASTERN UP 100KM CORRIDOR ---
    {
        "id": "prop_vns_1",
        "name": "Eldeco Surya Greens",
        "builder": "Eldeco Group",
        "builder_tier": "Tier 1 Regional Champion (North)",
        "city_id": "varanasi_100km",
        "city_name": "Varanasi & Eastern UP 100km Corridor",
        "micro_market": "Shivpur - North Varanasi Ridge",
        "lat": 25.3620,
        "lng": 82.9640,
        "bhk": "3 BHK Prime Gated",
        "avg_sqft": 1550,
        "price_per_sqft": 6900,
        "total_price_cr": 1.07,
        "monthly_maintenance_inr": 4200,
        "upfront_cash_required_lakhs": 27.5,
        "total_ownership_cost_cr": 1.16,
        "investment_score": 94.4,
        "growth_probability_pct": 93,
        "govt_master_plan_catalyst": "Varanasi 6-Lane Ring Road Phase 2 + Babatpur Airport 4-Lane Highway + Smart City Multi-Modal Hub",
        "road_distance_to_key_landmark_km": 5.8,
        "road_distance_to_school_benchmark_km": 2.8,
        "school_benchmark_name": "Sunbeam School Varuna",
        "elevation_m": 85,
        "flood_resilience_tag": "Zero Inundation (High Alluvial Ridge: +11m above Ganga HFL)",
        "water_infrastructure": {
            "piped_connection": "UP Jal Sansthan + Captive Tubewell Filtration",
            "has_stp": True,
            "has_water_softener": True,
            "has_water_meter": True,
            "has_gas_pipeline": True,
            "tanker_reliance_index": 1.0
        },
        "nearby_cbse_schools": [
            {"name": "Sunbeam School (Varuna / Cantt)", "distance_km": 2.8, "rating": 4.8, "annual_fees_class_1_to_5": "₹75K - ₹95K", "annual_fees_class_6_to_10": "₹95K - ₹1.25L", "annual_fees_class_11_to_12": "₹1.15L - ₹1.45L"}
        ],
        "google_maps_query": "Eldeco Surya Greens Shivpur Varanasi",
        "rera_url": "https://up-rera.in/"
    },
    {
        "id": "prop_vns_2",
        "name": "Omaxe Heights Prayagraj",
        "builder": "Omaxe Limited",
        "builder_tier": "Tier 1 National Player",
        "city_id": "varanasi_100km",
        "city_name": "Varanasi & Eastern UP 100km Corridor",
        "micro_market": "Civil Lines - Prayagraj",
        "lat": 25.4520,
        "lng": 81.8340,
        "bhk": "3 BHK Royal Luxury",
        "avg_sqft": 1720,
        "price_per_sqft": 8200,
        "total_price_cr": 1.41,
        "monthly_maintenance_inr": 5100,
        "upfront_cash_required_lakhs": 35.0,
        "total_ownership_cost_cr": 1.52,
        "investment_score": 93.5,
        "growth_probability_pct": 92,
        "govt_master_plan_catalyst": "Prayagraj Mahakumbh 2025 Infrastructure Works + 6-lane Ganga Expressway link to Meerut/Delhi",
        "road_distance_to_key_landmark_km": 1.5,
        "road_distance_to_school_benchmark_km": 1.8,
        "school_benchmark_name": "Boys' High School Prayagraj",
        "elevation_m": 98,
        "flood_resilience_tag": "Zero Inundation (British Grid Elevated Plateau: +14m above Sangam)",
        "water_infrastructure": {
            "piped_connection": "Jal Sansthan Piped Line 24x7",
            "has_stp": True,
            "has_water_softener": True,
            "has_water_meter": True,
            "has_gas_pipeline": True,
            "tanker_reliance_index": 0.5
        },
        "nearby_cbse_schools": [
            {"name": "Boys' High School and College", "distance_km": 1.8, "rating": 4.9, "annual_fees_class_1_to_5": "₹65K - ₹85K", "annual_fees_class_6_to_10": "₹85K - ₹1.10L", "annual_fees_class_11_to_12": "₹1.05L - ₹1.35L"}
        ],
        "google_maps_query": "Omaxe Heights Civil Lines Prayagraj",
        "rera_url": "https://up-rera.in/"
    },
    {
        "id": "prop_vns_3",
        "name": "Kashi Royal Greens",
        "builder": "Roma Builders",
        "builder_tier": "Tier 1 Regional Champion (Varanasi)",
        "city_id": "varanasi_100km",
        "city_name": "Varanasi & Eastern UP 100km Corridor",
        "micro_market": "Babatpur - Airport Corridor",
        "lat": 25.4410,
        "lng": 82.8620,
        "bhk": "3 BHK Airport Gated",
        "avg_sqft": 1480,
        "price_per_sqft": 5800,
        "total_price_cr": 0.86,
        "monthly_maintenance_inr": 3600,
        "upfront_cash_required_lakhs": 22.0,
        "total_ownership_cost_cr": 0.94,
        "investment_score": 93.1,
        "growth_probability_pct": 94,
        "govt_master_plan_catalyst": "LBS International Airport expansion (New Terminal & Cargo Complex) + Varanasi Ring Road Phase 2 interchange",
        "road_distance_to_key_landmark_km": 18.0,
        "road_distance_to_school_benchmark_km": 6.5,
        "school_benchmark_name": "Sunbeam School Babatpur",
        "elevation_m": 89,
        "flood_resilience_tag": "Zero Inundation (High Continental Plateau)",
        "water_infrastructure": {
            "piped_connection": "Deep Aquifer Tubewell with Multistage RO",
            "has_stp": True,
            "has_water_softener": True,
            "has_water_meter": True,
            "has_gas_pipeline": True,
            "tanker_reliance_index": 0.2
        },
        "nearby_cbse_schools": [
            {"name": "Delhi Public School (Varanasi NH-2)", "distance_km": 7.0, "rating": 4.7, "annual_fees_class_1_to_5": "₹90K - ₹1.15L", "annual_fees_class_6_to_10": "₹1.15L - ₹1.45L", "annual_fees_class_11_to_12": "₹1.35L - ₹1.70L"}
        ],
        "google_maps_query": "Babatpur Airport Varanasi",
        "rera_url": "https://up-rera.in/"
    }
]

# ==========================================
# 2. BEST RENTAL PROPERTIES (18 Properties: 3 per City)
# ==========================================
rental_properties = [
    # --- BENGALURU ---
    {
        "id": "rent_blr_1",
        "name": "Sobha Iris",
        "builder": "Sobha Limited",
        "city_id": "bengaluru",
        "city_name": "Bengaluru",
        "micro_market": "Outer Ring Road - Devarabisanahalli",
        "lat": 12.9298,
        "lng": 77.6915,
        "bhk": "3 BHK Luxury Furnished",
        "avg_sqft": 1710,
        "monthly_rent_inr": 82000,
        "monthly_maintenance_inr": 7500,
        "security_deposit_inr": 350000,
        "total_flat_value_cr": 2.15,
        "rental_yield_pct": 4.58,
        "rental_score": 95.2,
        "growth_probability_pct": 92,
        "govt_master_plan_catalyst": "Namma Metro Blue Line Kadubeesanahalli station walking distance (2026)",
        "commute_hub_distance_km": 0.4,
        "commute_hub_name": "Embassy TechVillage / RMZ Ecospace",
        "school_distance_km": 1.2,
        "school_name": "New Horizon Gurukul",
        "water_infrastructure": {"piped": True, "stp": True, "softener": True, "meter": True, "gas": True},
        "google_maps_query": "Sobha Iris Devarabisanahalli Bangalore"
    },
    {
        "id": "rent_blr_2",
        "name": "Prestige Ivy Terraces",
        "builder": "Prestige Group",
        "city_id": "bengaluru",
        "city_name": "Bengaluru",
        "micro_market": "Kadubeesanahalli - Bellandur East",
        "lat": 12.9320,
        "lng": 77.6940,
        "bhk": "3 BHK Premium Semi-Furnished",
        "avg_sqft": 1650,
        "monthly_rent_inr": 76000,
        "monthly_maintenance_inr": 6800,
        "security_deposit_inr": 300000,
        "total_flat_value_cr": 1.95,
        "rental_yield_pct": 4.68,
        "rental_score": 94.6,
        "growth_probability_pct": 90,
        "govt_master_plan_catalyst": "ORR Blue Line Metro + Cessna Business Park direct underpass access",
        "commute_hub_distance_km": 0.6,
        "commute_hub_name": "Cessna Business Park / Prestige Tech Park",
        "school_distance_km": 0.9,
        "school_name": "New Horizon Gurukul",
        "water_infrastructure": {"piped": True, "stp": True, "softener": True, "meter": True, "gas": True},
        "google_maps_query": "Prestige Ivy Terraces Kadubeesanahalli Bangalore"
    },
    {
        "id": "rent_blr_3",
        "name": "Assetz Marq 3.0",
        "builder": "Assetz Property Group",
        "city_id": "bengaluru",
        "city_name": "Bengaluru",
        "micro_market": "Whitefield - Kannamangala",
        "lat": 12.9980,
        "lng": 77.7540,
        "bhk": "3 BHK High-Rise Condo",
        "avg_sqft": 1620,
        "monthly_rent_inr": 65000,
        "monthly_maintenance_inr": 6200,
        "security_deposit_inr": 250000,
        "total_flat_value_cr": 1.70,
        "rental_yield_pct": 4.59,
        "rental_score": 93.8,
        "growth_probability_pct": 91,
        "govt_master_plan_catalyst": "Namma Metro Purple Line Kadugodi extension + STRR satellite bypass road",
        "commute_hub_distance_km": 3.2,
        "commute_hub_name": "ITPB Whitefield / EPIP Zone",
        "school_distance_km": 2.5,
        "school_name": "Delhi Public School Whitefield",
        "water_infrastructure": {"piped": True, "stp": True, "softener": True, "meter": True, "gas": True},
        "google_maps_query": "Assetz Marq Whitefield Bangalore"
    },

    # --- MUMBAI & MMR ---
    {
        "id": "rent_mum_1",
        "name": "L&T Emerald Isle",
        "builder": "L&T Realty",
        "city_id": "mumbai_mmr",
        "city_name": "Mumbai & MMR",
        "micro_market": "Powai - JVLR",
        "lat": 19.1240,
        "lng": 72.8980,
        "bhk": "2 BHK Luxury Condo",
        "avg_sqft": 920,
        "monthly_rent_inr": 78000,
        "monthly_maintenance_inr": 7200,
        "security_deposit_inr": 250000,
        "total_flat_value_cr": 2.45,
        "rental_yield_pct": 3.82,
        "rental_score": 94.8,
        "growth_probability_pct": 93,
        "govt_master_plan_catalyst": "Mumbai Metro Line 6 station directly in front of gate + JVLR signal-free lanes",
        "commute_hub_distance_km": 1.2,
        "commute_hub_name": "Nesco IT Park / Hiranandani Business Park",
        "school_distance_km": 1.5,
        "school_name": "Bombay Scottish Powai",
        "water_infrastructure": {"piped": True, "stp": True, "softener": True, "meter": True, "gas": True},
        "google_maps_query": "L&T Emerald Isle Powai Mumbai"
    },
    {
        "id": "rent_mum_2",
        "name": "Rustomjee Urbania",
        "builder": "Rustomjee",
        "city_id": "mumbai_mmr",
        "city_name": "Mumbai & MMR",
        "micro_market": "Majiwada - Thane West",
        "lat": 19.2080,
        "lng": 72.9860,
        "bhk": "2 BHK Township Unit",
        "avg_sqft": 860,
        "monthly_rent_inr": 42000,
        "monthly_maintenance_inr": 4500,
        "security_deposit_inr": 150000,
        "total_flat_value_cr": 1.28,
        "rental_yield_pct": 3.94,
        "rental_score": 92.5,
        "growth_probability_pct": 90,
        "govt_master_plan_catalyst": "Thane-Borivali Twin Underground Tunnel + Metro Line 4 (Wadala-Kasarvadavali)",
        "commute_hub_distance_km": 2.5,
        "commute_hub_name": "Ashar IT Park / Mindspace Airoli",
        "school_distance_km": 0.2,
        "school_name": "Rustomjee Cambridge International",
        "water_infrastructure": {"piped": True, "stp": True, "softener": True, "meter": True, "gas": True},
        "google_maps_query": "Rustomjee Urbania Majiwada Thane"
    },
    {
        "id": "rent_mum_3",
        "name": "Hiranandani Estate Rodas Enclave",
        "builder": "Hiranandani Group",
        "city_id": "mumbai_mmr",
        "city_name": "Mumbai & MMR",
        "micro_market": "Ghopbunder Road - Thane",
        "lat": 19.2550,
        "lng": 72.9750,
        "bhk": "3 BHK Signature",
        "avg_sqft": 1450,
        "monthly_rent_inr": 62000,
        "monthly_maintenance_inr": 6500,
        "security_deposit_inr": 220000,
        "total_flat_value_cr": 2.10,
        "rental_yield_pct": 3.54,
        "rental_score": 93.2,
        "growth_probability_pct": 91,
        "govt_master_plan_catalyst": "Ghopbunder elevated corridor + Thane-Navi Mumbai coastal ring road",
        "commute_hub_distance_km": 1.8,
        "commute_hub_name": "Quantum IT Park Thane",
        "school_distance_km": 0.8,
        "school_name": "Hiranandani Foundation School Thane",
        "water_infrastructure": {"piped": True, "stp": True, "softener": True, "meter": True, "gas": True},
        "google_maps_query": "Hiranandani Estate Thane"
    },

    # --- CHENNAI ---
    {
        "id": "rent_chn_1",
        "name": "Appaswamy Altezza",
        "builder": "Appaswamy Real Estates",
        "city_id": "chennai",
        "city_name": "Chennai",
        "micro_market": "OMR - Kottivakkam",
        "lat": 12.9780,
        "lng": 80.2510,
        "bhk": "3 BHK Sea Breeze",
        "avg_sqft": 1560,
        "monthly_rent_inr": 65000,
        "monthly_maintenance_inr": 6200,
        "security_deposit_inr": 300000,
        "total_flat_value_cr": 1.85,
        "rental_yield_pct": 4.22,
        "rental_score": 94.0,
        "growth_probability_pct": 92,
        "govt_master_plan_catalyst": "Chennai Metro Line 3 OMR corridor + Thiruvanmiyur beach bypass link",
        "commute_hub_distance_km": 1.8,
        "commute_hub_name": "Tidel Park / Ramanujan IT City",
        "school_distance_km": 2.1,
        "school_name": "The School - KFI",
        "water_infrastructure": {"piped": True, "stp": True, "softener": True, "meter": True, "gas": True},
        "google_maps_query": "Appaswamy Altezza OMR Chennai"
    },
    {
        "id": "rent_chn_2",
        "name": "Olympia Opaline",
        "builder": "Olympia Group",
        "city_id": "chennai",
        "city_name": "Chennai",
        "micro_market": "Navalur - Siruseri SIPCOT",
        "lat": 12.8420,
        "lng": 80.2280,
        "bhk": "3 BHK Lakeview",
        "avg_sqft": 1450,
        "monthly_rent_inr": 40000,
        "monthly_maintenance_inr": 4800,
        "security_deposit_inr": 180000,
        "total_flat_value_cr": 1.05,
        "rental_yield_pct": 4.57,
        "rental_score": 92.6,
        "growth_probability_pct": 90,
        "govt_master_plan_catalyst": "Metro Phase 2 terminus at Siruseri SIPCOT + 6-lane elevated expressway",
        "commute_hub_distance_km": 1.5,
        "commute_hub_name": "Siruseri IT SEZ / TCS Campus",
        "school_distance_km": 2.8,
        "school_name": "Hiranandani Upscale School",
        "water_infrastructure": {"piped": True, "stp": True, "softener": True, "meter": True, "gas": True},
        "google_maps_query": "Olympia Opaline Navalur Chennai"
    },
    {
        "id": "rent_chn_3",
        "name": "TVS Emerald Peninsula",
        "builder": "TVS Emerald",
        "city_id": "chennai",
        "city_name": "Chennai",
        "micro_market": "Manapakkam - Porur",
        "lat": 13.0210,
        "lng": 80.1740,
        "bhk": "3 BHK Corner Unit",
        "avg_sqft": 1520,
        "monthly_rent_inr": 50000,
        "monthly_maintenance_inr": 5200,
        "security_deposit_inr": 200000,
        "total_flat_value_cr": 1.38,
        "rental_yield_pct": 4.35,
        "rental_score": 93.1,
        "growth_probability_pct": 91,
        "govt_master_plan_catalyst": "Chennai Metro Corridor 4 (Poonamallee to Lighthouse) station at Porur",
        "commute_hub_distance_km": 2.0,
        "commute_hub_name": "DLF Cybercity Porur",
        "school_distance_km": 3.0,
        "school_name": "Lalaji Memorial Omega International",
        "water_infrastructure": {"piped": True, "stp": True, "softener": True, "meter": True, "gas": True},
        "google_maps_query": "TVS Emerald Peninsula Manapakkam Chennai"
    },

    # --- DELHI-NCR ---
    {
        "id": "rent_del_1",
        "name": "Tata Primanti",
        "builder": "Tata Housing",
        "city_id": "delhi_ncr",
        "city_name": "Delhi-NCR",
        "micro_market": "Southern Peripheral Road - Sec 72 Gurugram",
        "lat": 28.4120,
        "lng": 77.0340,
        "bhk": "3 BHK Luxury Executive",
        "avg_sqft": 2185,
        "monthly_rent_inr": 78000,
        "monthly_maintenance_inr": 8500,
        "security_deposit_inr": 200000,
        "total_flat_value_cr": 2.85,
        "rental_yield_pct": 3.28,
        "rental_score": 93.6,
        "growth_probability_pct": 92,
        "govt_master_plan_catalyst": "SPR 8-lane cloverleaf upgrade + Direct connect to Cyber City via Golf Course Ext Rd",
        "commute_hub_distance_km": 3.5,
        "commute_hub_name": "Cyber City / Vatika Business Park",
        "school_distance_km": 3.0,
        "school_name": "The Heritage School Gurugram",
        "water_infrastructure": {"piped": True, "stp": True, "softener": True, "meter": True, "gas": True},
        "google_maps_query": "Tata Primanti Sector 72 Gurgaon"
    },
    {
        "id": "rent_del_2",
        "name": "Godrej Woods",
        "builder": "Godrej Properties",
        "city_id": "delhi_ncr",
        "city_name": "Delhi-NCR",
        "micro_market": "Sector 43 - Central Noida",
        "lat": 28.5630,
        "lng": 77.3480,
        "bhk": "3 BHK Forest Theme",
        "avg_sqft": 1850,
        "monthly_rent_inr": 72000,
        "monthly_maintenance_inr": 6800,
        "security_deposit_inr": 180000,
        "total_flat_value_cr": 2.25,
        "rental_yield_pct": 3.84,
        "rental_score": 94.2,
        "growth_probability_pct": 94,
        "govt_master_plan_catalyst": "Noida Golf Course Metro station adjacent + Botanical Garden interchange (Blue/Magenta lines)",
        "commute_hub_distance_km": 2.0,
        "commute_hub_name": "Film City / Sector 62 IT Hub",
        "school_distance_km": 2.5,
        "school_name": "Step by Step School",
        "water_infrastructure": {"piped": True, "stp": True, "softener": True, "meter": True, "gas": True},
        "google_maps_query": "Godrej Woods Sector 43 Noida"
    },
    {
        "id": "rent_del_3",
        "name": "Mahagun Moderne",
        "builder": "Mahagun Group",
        "city_id": "delhi_ncr",
        "city_name": "Delhi-NCR",
        "micro_market": "Sector 78 - Central Noida",
        "lat": 28.5720,
        "lng": 77.3850,
        "bhk": "3 BHK Premium Gated",
        "avg_sqft": 1550,
        "monthly_rent_inr": 48000,
        "monthly_maintenance_inr": 4500,
        "security_deposit_inr": 100000,
        "total_flat_value_cr": 1.45,
        "rental_yield_pct": 3.97,
        "rental_score": 93.0,
        "growth_probability_pct": 91,
        "govt_master_plan_catalyst": "Noida Sector 76 Aqua Line Metro station within 400m + FNG Expressway ramp",
        "commute_hub_distance_km": 2.8,
        "commute_hub_name": "Advant Navis Business Park",
        "school_distance_km": 1.8,
        "school_name": "Manthan School Noida",
        "water_infrastructure": {"piped": True, "stp": True, "softener": True, "meter": True, "gas": True},
        "google_maps_query": "Mahagun Moderne Sector 78 Noida"
    },

    # --- HYDERABAD ---
    {
        "id": "rent_hyd_1",
        "name": "Aparna Serene Park",
        "builder": "Aparna Constructions",
        "city_id": "hyderabad",
        "city_name": "Hyderabad",
        "micro_market": "Gachibowli - Kondapur",
        "lat": 17.4610,
        "lng": 78.3540,
        "bhk": "3 BHK Gated High-Rise",
        "avg_sqft": 1710,
        "monthly_rent_inr": 62000,
        "monthly_maintenance_inr": 5500,
        "security_deposit_inr": 150000,
        "total_flat_value_cr": 1.75,
        "rental_yield_pct": 4.25,
        "rental_score": 95.0,
        "growth_probability_pct": 94,
        "govt_master_plan_catalyst": "Kondapur to Gachibowli 4-lane flyover + Metro Phase 2 Airport Express line link",
        "commute_hub_distance_km": 2.1,
        "commute_hub_name": "Financial District / Mindspace HITECH City",
        "school_distance_km": 2.5,
        "school_name": "CHIREC International School",
        "water_infrastructure": {"piped": True, "stp": True, "softener": True, "meter": True, "gas": True},
        "google_maps_query": "Aparna Serene Park Kondapur Hyderabad"
    },
    {
        "id": "rent_hyd_2",
        "name": "Rajapushpa Provincia",
        "builder": "Rajapushpa Properties",
        "city_id": "hyderabad",
        "city_name": "Hyderabad",
        "micro_market": "Narsingi - Financial District",
        "lat": 17.3820,
        "lng": 78.3620,
        "bhk": "3 BHK Ultra-Luxury",
        "avg_sqft": 2020,
        "monthly_rent_inr": 68000,
        "monthly_maintenance_inr": 6000,
        "security_deposit_inr": 180000,
        "total_flat_value_cr": 2.05,
        "rental_yield_pct": 3.98,
        "rental_score": 94.1,
        "growth_probability_pct": 95,
        "govt_master_plan_catalyst": "Neopolis Kokapet Trumpet Interchange + ORR Exit 1 connectivity",
        "commute_hub_distance_km": 3.0,
        "commute_hub_name": "Continental Hospital / WaveRock Tech Park",
        "school_distance_km": 2.8,
        "school_name": "Oakridge International School",
        "water_infrastructure": {"piped": True, "stp": True, "softener": True, "meter": True, "gas": True},
        "google_maps_query": "Rajapushpa Provincia Narsingi Hyderabad"
    },
    {
        "id": "rent_hyd_3",
        "name": "My Home Avatar",
        "builder": "My Home Group",
        "city_id": "hyderabad",
        "city_name": "Hyderabad",
        "micro_market": "Puppalaguda - Financial District",
        "lat": 17.4060,
        "lng": 78.3580,
        "bhk": "3 BHK Master Township",
        "avg_sqft": 1834,
        "monthly_rent_inr": 64000,
        "monthly_maintenance_inr": 5800,
        "security_deposit_inr": 160000,
        "total_flat_value_cr": 1.90,
        "rental_yield_pct": 4.04,
        "rental_score": 94.4,
        "growth_probability_pct": 94,
        "govt_master_plan_catalyst": "ORR service road multi-tier underpass to Wipro Circle",
        "commute_hub_distance_km": 2.5,
        "commute_hub_name": "Amazon HQ / Microsoft Campus",
        "school_distance_km": 2.6,
        "school_name": "Oakridge International",
        "water_infrastructure": {"piped": True, "stp": True, "softener": True, "meter": True, "gas": True},
        "google_maps_query": "My Home Avatar Puppalaguda Hyderabad"
    },

    # --- VARANASI & EASTERN UP 100KM CORRIDOR ---
    {
        "id": "rent_vns_1",
        "name": "Eldeco Anandam Residency",
        "builder": "Eldeco Group",
        "city_id": "varanasi_100km",
        "city_name": "Varanasi & Eastern UP 100km Corridor",
        "micro_market": "Civil Lines - Prayagraj",
        "lat": 25.4560,
        "lng": 81.8410,
        "bhk": "3 BHK Executive",
        "avg_sqft": 1450,
        "monthly_rent_inr": 34000,
        "monthly_maintenance_inr": 3800,
        "security_deposit_inr": 70000,
        "total_flat_value_cr": 0.98,
        "rental_yield_pct": 4.16,
        "rental_score": 93.0,
        "growth_probability_pct": 91,
        "govt_master_plan_catalyst": "Civil Lines Smart City Transit Corridor + High Court administrative hub",
        "commute_hub_distance_km": 1.2,
        "commute_hub_name": "Allahabad High Court / AG Office",
        "school_distance_km": 1.5,
        "school_name": "Boys' High School Prayagraj",
        "water_infrastructure": {"piped": True, "stp": True, "softener": True, "meter": True, "gas": True},
        "google_maps_query": "Eldeco Civil Lines Prayagraj"
    },
    {
        "id": "rent_vns_2",
        "name": "Kashi Smart City Towers",
        "builder": "Kashi Infra Developers",
        "city_id": "varanasi_100km",
        "city_name": "Varanasi & Eastern UP 100km Corridor",
        "micro_market": "Shivpur - Cantt Varanasi",
        "lat": 25.3580,
        "lng": 82.9710,
        "bhk": "3 BHK Premium Gated",
        "avg_sqft": 1400,
        "monthly_rent_inr": 28000,
        "monthly_maintenance_inr": 3200,
        "security_deposit_inr": 60000,
        "total_flat_value_cr": 0.82,
        "rental_yield_pct": 4.10,
        "rental_score": 92.4,
        "growth_probability_pct": 92,
        "govt_master_plan_catalyst": "Varanasi Ropeway Phase 1 + Cantt multi-modal transport hub",
        "commute_hub_distance_km": 3.0,
        "commute_hub_name": "Varanasi Cantt / Commissionerate",
        "school_distance_km": 2.2,
        "school_name": "Sunbeam School Varuna",
        "water_infrastructure": {"piped": True, "stp": True, "softener": True, "meter": True, "gas": True},
        "google_maps_query": "Shivpur Varanasi"
    },
    {
        "id": "rent_vns_3",
        "name": "Sangam Vihar Residency",
        "builder": "Omaxe Limited",
        "city_id": "varanasi_100km",
        "city_name": "Varanasi & Eastern UP 100km Corridor",
        "micro_market": "Jhalwa - IT Park Prayagraj",
        "lat": 25.4350,
        "lng": 81.7720,
        "bhk": "3 BHK Academic Suite",
        "avg_sqft": 1380,
        "monthly_rent_inr": 25000,
        "monthly_maintenance_inr": 2800,
        "security_deposit_inr": 50000,
        "total_flat_value_cr": 0.72,
        "rental_yield_pct": 4.17,
        "rental_score": 92.0,
        "growth_probability_pct": 90,
        "govt_master_plan_catalyst": "IIIT Prayagraj incubation corridor + 4-lane Subedarganj terminal bypass",
        "commute_hub_distance_km": 1.0,
        "commute_hub_name": "IIIT Allahabad / Subedarganj Rail Terminal",
        "school_distance_km": 2.5,
        "school_name": "St. Mary's Convent",
        "water_infrastructure": {"piped": True, "stp": True, "softener": True, "meter": True, "gas": True},
        "google_maps_query": "Jhalwa Prayagraj"
    }
]

# ==========================================
# 3. BEST GATED COMMUNITY PLOTS & SITES (18 Layouts: 3 per City)
# ==========================================
gated_plots = [
    # --- BENGALURU ---
    {
        "id": "plot_blr_1",
        "name": "Prestige Great Acres",
        "developer": "Prestige Group",
        "city_id": "bengaluru",
        "city_name": "Bengaluru",
        "location": "The Prestige City, Sarjapur Road",
        "lat": 12.8720,
        "lng": 77.7460,
        "plot_sizes_sqft": "1,500 - 4,000 sqft",
        "price_per_sqft": 8900,
        "total_price_lakhs": "₹133.5 Lakhs - ₹356.0 Lakhs",
        "plotted_appreciation_score": 95.8,
        "growth_probability_pct": 94,
        "govt_master_plan_catalyst": "STRR (Satellite Town Ring Road) NH-948A connectivity + Sarjapur Metro Phase 3 Line (Sarjapur to Hebbal 37km)",
        "elevation_m": 896,
        "soil_percolation": "Red Sandy Loam (Rapid natural percolation, zero water stagnation)",
        "drainage_outfall": "Engineered RCC Box Storm Drains connected to external master storm network",
        "approval_authority": "BMRDA & RERA Approved (PRM/KA/RERA/1251/308/PR/210824/004289)",
        "flood_risk_tag": "Zero Inundation (High Ridge Saddle)",
        "google_maps_query": "Prestige Great Acres Sarjapur Bangalore",
        "validation_url": "https://rera.karnataka.gov.in/"
    },
    {
        "id": "plot_blr_2",
        "name": "Brigade Oasis",
        "developer": "Brigade Group",
        "city_id": "bengaluru",
        "city_name": "Bengaluru",
        "location": "Devanahalli - Airport Corridor",
        "lat": 13.2450,
        "lng": 77.7120,
        "plot_sizes_sqft": "1,200 - 3,200 sqft",
        "price_per_sqft": 6400,
        "total_price_lakhs": "₹76.8 Lakhs - ₹204.8 Lakhs",
        "plotted_appreciation_score": 94.5,
        "growth_probability_pct": 95,
        "govt_master_plan_catalyst": "Bengaluru Airport City SEZ + KIADB Aerospace & Hardware Park + Blue Line Airport Metro (2026)",
        "elevation_m": 925,
        "soil_percolation": "Alluvial gravely loam, zero water retention",
        "drainage_outfall": "Rainwater harvesting recharge pits at every 30m interval",
        "approval_authority": "BIAAPA & RERA Approved",
        "flood_risk_tag": "Zero Inundation (High Continental Divide)",
        "google_maps_query": "Brigade Oasis Devanahalli Bangalore",
        "validation_url": "https://rera.karnataka.gov.in/"
    },
    {
        "id": "plot_blr_3",
        "name": "Sobha Oakshire",
        "developer": "Sobha Limited",
        "city_id": "bengaluru",
        "city_name": "Bengaluru",
        "location": "IVC Road - Devanahalli",
        "lat": 13.2280,
        "lng": 77.6740,
        "plot_sizes_sqft": "1,800 - 3,500 sqft",
        "price_per_sqft": 7800,
        "total_price_lakhs": "₹140.4 Lakhs - ₹273.0 Lakhs",
        "plotted_appreciation_score": 94.2,
        "growth_probability_pct": 94,
        "govt_master_plan_catalyst": "300ft IVC Expressway linking Kempegowda Airport to STRR & Doddaballapur industrial corridor",
        "elevation_m": 918,
        "soil_percolation": "Permeable red murrum, naturally self-draining",
        "drainage_outfall": "Natural contours slope to percolation trenches",
        "approval_authority": "BIAAPA Approved & Karnataka RERA Registered",
        "flood_risk_tag": "Zero Inundation (Natural Granitic Plateau)",
        "google_maps_query": "Sobha Oakshire IVC Road Bangalore",
        "validation_url": "https://rera.karnataka.gov.in/"
    },

    # --- MUMBAI & MMR ---
    {
        "id": "plot_mum_1",
        "name": "Hiranandani Fortune City Plotted Enclave",
        "developer": "Hiranandani Communities",
        "city_id": "mumbai_mmr",
        "city_name": "Mumbai & MMR",
        "location": "Panvel - Bhokarpada MMR",
        "lat": 18.9680,
        "lng": 73.1650,
        "plot_sizes_sqft": "1,800 - 4,500 sqft",
        "price_per_sqft": 9200,
        "total_price_lakhs": "₹165.6 Lakhs - ₹414.0 Lakhs",
        "plotted_appreciation_score": 95.4,
        "growth_probability_pct": 96,
        "govt_master_plan_catalyst": "Navi Mumbai International Airport (15 mins) + Virar-Alibaug Multi-Modal Corridor + Mumbai Trans-Harbour Link (MTHL)",
        "elevation_m": 35,
        "soil_percolation": "Basaltic murrum with fast gravitational runoff to Prabalmachi stream",
        "drainage_outfall": "Dual trapezoidal contour drains with silt traps",
        "approval_authority": "CIDCO / NA Permission / MahaRERA Approved",
        "flood_risk_tag": "Zero Inundation (Elevated Foothills Plateau)",
        "google_maps_query": "Hiranandani Fortune City Panvel Navi Mumbai",
        "validation_url": "https://maharera.mahaonline.gov.in/"
    },
    {
        "id": "plot_mum_2",
        "name": "Godrej Woodland Plotted County",
        "developer": "Godrej Properties",
        "city_id": "mumbai_mmr",
        "city_name": "Mumbai & MMR",
        "location": "Khalapur - Mumbai-Pune Expressway",
        "lat": 18.8250,
        "lng": 73.2840,
        "plot_sizes_sqft": "1,500 - 3,500 sqft",
        "price_per_sqft": 4800,
        "total_price_lakhs": "₹72.0 Lakhs - ₹168.0 Lakhs",
        "plotted_appreciation_score": 93.0,
        "growth_probability_pct": 92,
        "govt_master_plan_catalyst": "Navi Mumbai Airport influence zone + Mumbai-Pune Expressway 8-lane missing link bypass",
        "elevation_m": 62,
        "soil_percolation": "Laterite hilly gravel with instantaneous runoff",
        "drainage_outfall": "Natural mountain swales and retention ponds",
        "approval_authority": "MahaRERA & Town Planning Sanctioned",
        "flood_risk_tag": "Zero Inundation (Mountain Ridge)",
        "google_maps_query": "Khalapur Maharashtra",
        "validation_url": "https://maharera.mahaonline.gov.in/"
    },
    {
        "id": "plot_mum_3",
        "name": "Lodha Codename Golden Sunrise",
        "developer": "Lodha / Macrotech",
        "city_id": "mumbai_mmr",
        "city_name": "Mumbai & MMR",
        "location": "Dombivli East - Palava Smart City",
        "lat": 19.1820,
        "lng": 73.0850,
        "plot_sizes_sqft": "1,200 - 2,500 sqft",
        "price_per_sqft": 6500,
        "total_price_lakhs": "₹78.0 Lakhs - ₹162.5 Lakhs",
        "plotted_appreciation_score": 93.6,
        "growth_probability_pct": 93,
        "govt_master_plan_catalyst": "Kalyan-Taloja Metro Line 12 + Airoli-Katai Naka tunnel freeway",
        "elevation_m": 24,
        "soil_percolation": "Hard murrum plateau, engineered stormwater retention lake",
        "drainage_outfall": "Sub-surface storm conduits to Palava eco-retention channels",
        "approval_authority": "MahaRERA Registered & KDMC Sanctioned",
        "flood_risk_tag": "Zero Inundation (Engineered Township Tableland)",
        "google_maps_query": "Palava Smart City Dombivli",
        "validation_url": "https://maharera.mahaonline.gov.in/"
    },

    # --- CHENNAI ---
    {
        "id": "plot_chn_1",
        "name": "TVS Emerald Hamlet",
        "developer": "TVS Emerald",
        "city_id": "chennai",
        "city_name": "Chennai",
        "location": "Karapakkam - OMR IT Corridor",
        "lat": 12.9150,
        "lng": 80.2280,
        "plot_sizes_sqft": "1,200 - 3,000 sqft",
        "price_per_sqft": 7500,
        "total_price_lakhs": "₹90.0 Lakhs - ₹225.0 Lakhs",
        "plotted_appreciation_score": 94.0,
        "growth_probability_pct": 92,
        "govt_master_plan_catalyst": "CMDA Master Plan 2026 OMR elevated 6-lane highway + Metro Phase 2 Sholinganallur junction",
        "elevation_m": 14,
        "soil_percolation": "Sandy loam with immediate absorption",
        "drainage_outfall": "Dedicated outfall to GCC Buckingham canal regulator",
        "approval_authority": "CMDA & TNRERA Approved",
        "flood_risk_tag": "Zero Inundation (High Natural Dune Ridge: +4.5m above marshland datum)",
        "google_maps_query": "TVS Emerald Hamlet Karapakkam Chennai",
        "validation_url": "https://www.rera.tn.gov.in/"
    },
    {
        "id": "plot_chn_2",
        "name": "Casagrand Platinum Gated Plots",
        "developer": "Casagrand Builder",
        "city_id": "chennai",
        "city_name": "Chennai",
        "location": "Perungalathur - GST Road",
        "lat": 12.8980,
        "lng": 80.0860,
        "plot_sizes_sqft": "1,200 - 2,400 sqft",
        "price_per_sqft": 4800,
        "total_price_lakhs": "₹57.6 Lakhs - ₹115.2 Lakhs",
        "plotted_appreciation_score": 92.2,
        "growth_probability_pct": 91,
        "govt_master_plan_catalyst": "Kilambakkam Bus Terminus (KCBT) operational + Chennai Metro Airport to Kilambakkam extension",
        "elevation_m": 22,
        "soil_percolation": "Red gravely clay loam, good drainage",
        "drainage_outfall": "Internal storm drains connecting to GST Road highway canal",
        "approval_authority": "CMDA Approved & TNRERA Registered",
        "flood_risk_tag": "Zero Inundation (High GST Ridge)",
        "google_maps_query": "Perungalathur Chennai",
        "validation_url": "https://www.rera.tn.gov.in/"
    },
    {
        "id": "plot_chn_3",
        "name": "Purva Raagam Plotted Haven",
        "developer": "Puravankara Limited",
        "city_id": "chennai",
        "city_name": "Chennai",
        "location": "Thirumazhisai - Bangalore Highway NH-48",
        "lat": 13.0580,
        "lng": 80.0610,
        "plot_sizes_sqft": "1,200 - 3,200 sqft",
        "price_per_sqft": 4200,
        "total_price_lakhs": "₹50.4 Lakhs - ₹134.4 Lakhs",
        "plotted_appreciation_score": 92.8,
        "growth_probability_pct": 93,
        "govt_master_plan_catalyst": "Chennai Metro Corridor 4 terminating station + Greenfield Parandur Airport Expressway link",
        "elevation_m": 28,
        "soil_percolation": "Coarse sandy gravel, rapid infiltration",
        "drainage_outfall": "Dedicated subterranean RCC stormwater drains",
        "approval_authority": "CMDA Sanctioned & TNRERA Approved",
        "flood_risk_tag": "Zero Inundation (High Interfluvial Ridge)",
        "google_maps_query": "Thirumazhisai Chennai",
        "validation_url": "https://www.rera.tn.gov.in/"
    },

    # --- DELHI-NCR ---
    {
        "id": "plot_del_1",
        "name": "DLF Alameda Plots",
        "developer": "DLF Limited",
        "city_id": "delhi_ncr",
        "city_name": "Delhi-NCR",
        "location": "Sector 73, Southern Peripheral Road, Gurugram",
        "lat": 28.4110,
        "lng": 77.0210,
        "plot_sizes_sqft": "4,050 - 9,000 sqft (450 - 1000 sq yd)",
        "price_per_sqft": 19500,
        "total_price_lakhs": "₹789.7 Lakhs - ₹1,755.0 Lakhs",
        "plotted_appreciation_score": 96.8,
        "growth_probability_pct": 95,
        "govt_master_plan_catalyst": "SPR 60m right-of-way expansion + Gurugram Central Elevated Highway + Cloverleaf interchange to NH-48 & CPR",
        "elevation_m": 232,
        "soil_percolation": "Semi-arid sandy loam, rapid storm absorption",
        "drainage_outfall": "Underground Stormwater Network connected to GMDA Sector Trunk Storm Drain",
        "approval_authority": "DTCP Haryana Licenced Colony & HARERA Registered",
        "flood_risk_tag": "Zero Inundation (High Natural Interfluvial Ridge)",
        "google_maps_query": "DLF Alameda Sector 73 Gurgaon",
        "validation_url": "https://haryanarera.gov.in/"
    },
    {
        "id": "plot_del_2",
        "name": "Signature Global Park Plots",
        "developer": "Signature Global",
        "city_id": "delhi_ncr",
        "city_name": "Delhi-NCR",
        "location": "Sector 36 Sohna - South of Gurugram",
        "lat": 28.2560,
        "lng": 77.0540,
        "plot_sizes_sqft": "1,080 - 2,250 sqft",
        "price_per_sqft": 8200,
        "total_price_lakhs": "₹88.5 Lakhs - ₹184.5 Lakhs",
        "plotted_appreciation_score": 94.0,
        "growth_probability_pct": 93,
        "govt_master_plan_catalyst": "Sohna Elevated Expressway (15 mins to Subhash Chowk) + Delhi-Mumbai Expressway starting interchange",
        "elevation_m": 248,
        "soil_percolation": "Aravali foothill gravel, high natural runoff",
        "drainage_outfall": "Perimeter retention bunds and storm sewer line",
        "approval_authority": "DTCP Deen Dayal Jan Awas Yojna (DDJAY) & HARERA",
        "flood_risk_tag": "Zero Inundation (Elevated Foothill Gradient)",
        "google_maps_query": "Sector 36 Sohna Gurgaon",
        "validation_url": "https://haryanarera.gov.in/"
    },
    {
        "id": "plot_del_3",
        "name": "Godrej Palm Retreat Plotted Enclave",
        "developer": "Godrej Properties",
        "city_id": "delhi_ncr",
        "city_name": "Delhi-NCR",
        "location": "Sector 150 - Noida Expressway",
        "lat": 28.4320,
        "lng": 77.4920,
        "plot_sizes_sqft": "1,800 - 4,500 sqft",
        "price_per_sqft": 14200,
        "total_price_lakhs": "₹255.6 Lakhs - ₹639.0 Lakhs",
        "plotted_appreciation_score": 95.0,
        "growth_probability_pct": 95,
        "govt_master_plan_catalyst": "Direct expressway link to Noida International Airport Jewar + Multi-modal transit hub",
        "elevation_m": 205,
        "soil_percolation": "Engineered sand gravel bed with rapid drainage fall",
        "drainage_outfall": "Dual underground box storm drain network connected to Noida Authority sector trunk",
        "approval_authority": "Noida Authority Sanctioned & UP RERA Registered",
        "flood_risk_tag": "Zero Inundation (High Engineered Plinth)",
        "google_maps_query": "Sector 150 Noida",
        "validation_url": "https://up-rera.in/"
    },

    # --- HYDERABAD ---
    {
        "id": "plot_hyd_1",
        "name": "My Home Ankura Plotted Enclave",
        "developer": "My Home Group",
        "city_id": "hyderabad",
        "city_name": "Hyderabad",
        "location": "Tellapur - Financial District Extn",
        "lat": 17.4810,
        "lng": 78.2910,
        "plot_sizes_sqft": "2,400 - 4,800 sqft",
        "price_per_sqft": 9800,
        "total_price_lakhs": "₹235.2 Lakhs - ₹470.4 Lakhs",
        "plotted_appreciation_score": 95.6,
        "growth_probability_pct": 96,
        "govt_master_plan_catalyst": "Hyderabad Radial Road 7 expansion + Tellapur to Kokapet Trumpet Interchange + Multi-Modal MMTS Tellapur station",
        "elevation_m": 574,
        "soil_percolation": "Granite weathered red soil (High percolation gradient)",
        "drainage_outfall": "GHMC SNDP master RCC stormwater outfall",
        "approval_authority": "HMDA & TSRERA Registered",
        "flood_risk_tag": "Zero Inundation (High Granitic Ridge)",
        "google_maps_query": "My Home Ankura Tellapur Hyderabad",
        "validation_url": "https://rera.telangana.gov.in/"
    },
    {
        "id": "plot_hyd_2",
        "name": "Aparna Dharti Gated Plots",
        "developer": "Aparna Constructions",
        "city_id": "hyderabad",
        "city_name": "Hyderabad",
        "location": "Dundigal - ORR Exit 5",
        "lat": 17.5840,
        "lng": 78.4120,
        "plot_sizes_sqft": "1,800 - 3,600 sqft",
        "price_per_sqft": 5200,
        "total_price_lakhs": "₹93.6 Lakhs - ₹187.2 Lakhs",
        "plotted_appreciation_score": 93.2,
        "growth_probability_pct": 92,
        "govt_master_plan_catalyst": "Hyderabad Regional Ring Road (RRR) northern quadrant + Medchal pharmaceutical logistics hub",
        "elevation_m": 598,
        "soil_percolation": "Red gravel soil, zero water accumulation",
        "drainage_outfall": "Internal concrete box storm drains",
        "approval_authority": "HMDA & TSRERA Registered",
        "flood_risk_tag": "Zero Inundation (Highest Elevation Plateau in Hyderabad: 598m)",
        "google_maps_query": "Dundigal Hyderabad",
        "validation_url": "https://rera.telangana.gov.in/"
    },
    {
        "id": "plot_hyd_3",
        "name": "Rajapushpa Green Dale Plots",
        "developer": "Rajapushpa Properties",
        "city_id": "hyderabad",
        "city_name": "Hyderabad",
        "location": "Tellapur - Osmansagar Ridge",
        "lat": 17.4680,
        "lng": 78.2840,
        "plot_sizes_sqft": "2,700 - 5,400 sqft",
        "price_per_sqft": 10500,
        "total_price_lakhs": "₹283.5 Lakhs - ₹567.0 Lakhs",
        "plotted_appreciation_score": 95.0,
        "growth_probability_pct": 95,
        "govt_master_plan_catalyst": "Neopolis 100ft arterial link + Gopanpally flyover to Financial District",
        "elevation_m": 568,
        "soil_percolation": "Rocky basaltic terrain, zero water retention",
        "drainage_outfall": "Engineered cascade stormwater collectors",
        "approval_authority": "HMDA Approved Layout & TSRERA",
        "flood_risk_tag": "Zero Inundation (High Continental Divide Ridge)",
        "google_maps_query": "Rajapushpa Green Dale Tellapur",
        "validation_url": "https://rera.telangana.gov.in/"
    },

    # --- VARANASI & EASTERN UP 100KM CORRIDOR ---
    {
        "id": "plot_vns_1",
        "name": "Eldeco Shaurya Gated Plots",
        "developer": "Eldeco Group",
        "city_id": "varanasi_100km",
        "city_name": "Varanasi & Eastern UP 100km Corridor",
        "location": "Varanasi-Lucknow NH-56 Highway, Shivpur Extn",
        "lat": 25.3780,
        "lng": 82.9350,
        "plot_sizes_sqft": "1,350 - 3,600 sqft (150 - 400 sq yd)",
        "price_per_sqft": 4500,
        "total_price_lakhs": "₹60.7 Lakhs - ₹162.0 Lakhs",
        "plotted_appreciation_score": 94.6,
        "growth_probability_pct": 94,
        "govt_master_plan_catalyst": "Varanasi Ring Road Phase 2 + Babatpur Airport Aero-City Logistic Zone + Kashi Integrated Smart Transit Hub",
        "elevation_m": 88,
        "soil_percolation": "High coarse silt-loam terrace (Immune to Ganga & Varuna backwaters: +14m above Ganga 1978 HFL)",
        "drainage_outfall": "Gravity-fed underground storm sewer discharging away from Varuna river basin",
        "approval_authority": "VDA (Varanasi Development Authority) Sanctioned & UP RERA Registered",
        "flood_risk_tag": "Zero Inundation (Immune High Terrace: 88m MSL vs Ganga HFL 73.9m)",
        "google_maps_query": "Eldeco Shaurya Shivpur Varanasi",
        "validation_url": "https://up-rera.in/"
    },
    {
        "id": "plot_vns_2",
        "name": "PDA Sangam Vihar Gated Plotted Scheme",
        "developer": "Prayagraj Development Authority (PDA)",
        "city_id": "varanasi_100km",
        "city_name": "Varanasi & Eastern UP 100km Corridor",
        "location": "Civil Lines Extn - Jhalwa Elevated Sector, Prayagraj",
        "lat": 25.4380,
        "lng": 81.7760,
        "plot_sizes_sqft": "1,800 - 4,500 sqft (200 - 500 sq yd)",
        "price_per_sqft": 4800,
        "total_price_lakhs": "₹86.4 Lakhs - ₹216.0 Lakhs",
        "plotted_appreciation_score": 93.8,
        "growth_probability_pct": 93,
        "govt_master_plan_catalyst": "Prayagraj Mahakumbh 2025 Transit Grid + IIIT Prayagraj Knowledge Park + Direct Ganga Expressway Ramp",
        "elevation_m": 102,
        "soil_percolation": "Consolidated alluvial ridge, natural gravity stormwater fall into Sasur Khaderi ravine",
        "drainage_outfall": "PDA master storm drain network",
        "approval_authority": "PDA Statutory Government Scheme & Freehold Registry",
        "flood_risk_tag": "Zero Inundation (High Alluvial Ridge: 102m MSL vs Sangam HFL 84.7m)",
        "google_maps_query": "PDA Sangam Vihar Jhalwa Prayagraj",
        "validation_url": "https://up-rera.in/"
    },
    {
        "id": "plot_vns_3",
        "name": "Mirzapur Vindhya Enclave Gated Plots",
        "developer": "Roma Builders & Promoters",
        "city_id": "varanasi_100km",
        "city_name": "Varanasi & Eastern UP 100km Corridor",
        "location": "Vindhyachal Corridor Highway NH-135, Mirzapur",
        "lat": 25.1580,
        "lng": 82.5240,
        "plot_sizes_sqft": "1,500 - 3,000 sqft",
        "price_per_sqft": 3200,
        "total_price_lakhs": "₹48.0 Lakhs - ₹96.0 Lakhs",
        "plotted_appreciation_score": 92.5,
        "growth_probability_pct": 92,
        "govt_master_plan_catalyst": "Maa Vindhyavasini Temple Corridor Pilgrimage Redevelopment + Dedicated 4-lane Ring Highway to Varanasi",
        "elevation_m": 94,
        "soil_percolation": "Sandstone rocky base with fast surface gradient to natural hill ravines",
        "drainage_outfall": "Gravity swales directing stormwater away from residential parcels",
        "approval_authority": "VDA & UP RERA Registered",
        "flood_risk_tag": "Zero Inundation (High Vindhyan Foothill Ridge)",
        "google_maps_query": "Vindhyachal Mirzapur",
        "validation_url": "https://up-rera.in/"
    }
]

# Write JSONs
with open(os.path.join(DATA_DIR, "properties.json"), "w", encoding="utf-8") as f:
    json.dump(properties, f, indent=2, ensure_ascii=False)

with open(os.path.join(DATA_DIR, "rental_properties.json"), "w", encoding="utf-8") as f:
    json.dump(rental_properties, f, indent=2, ensure_ascii=False)

with open(os.path.join(DATA_DIR, "gated_plots.json"), "w", encoding="utf-8") as f:
    json.dump(gated_plots, f, indent=2, ensure_ascii=False)

print(f"Generated properties.json ({len(properties)}), rental_properties.json ({len(rental_properties)}), and gated_plots.json ({len(gated_plots)}) successfully.")
